### PR TITLE
Update default_grouping.md

### PR DESCRIPTION
**Pull request by kai-thomas-datadog**
add details to default grouping

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by drichards-87 — APPROVED** [review]
Looks good. Is this ready to be merged now?

**Comment by kai-thomas-datadog** [comment]
I'm not sure, for some reason it's not passing the 'Preview Synthetics' test. Do you know why that might be?

**Comment by drichards-87** [comment]
> I'm not sure, for some reason it's not passing the 'Preview Synthetics' test. Do you know why that might be?

Ah, it's because the branch name is missing a forward slash. We require a forward slash in order to generate a staging preview of the docs site. This requirement also has the side effect of not allowing the build job to fully pass when a branch is missing it.

**Comment by kai-thomas-datadog** [comment]
Okay, thanks :). It's ready

**Pull request merged**
