### PR TITLE
added overview screenshot and moved tracing screenshot down

### PR DESCRIPTION
**Pull request by barieom**
### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by brett0000FF — CHANGES_REQUESTED** [review]
@barieom - Hey there! It looks like there isn't a new screenshot in this PR? If you look at the preview site, nothing shows up for `llm-observability-landing.png`.

**Review by Yun-Kim — APPROVED** [review]
LGTM from ml obs side!

**Comment by barieom** [comment]
> @barieom - Hey there! It looks like there isn't a new screenshot in this PR? If you look at the preview site, nothing shows up for `llm-observability-landing.png`.

Hey @brett0000FF - the png wasn't committed but should be included now

**Review by brett0000FF — APPROVED** [review]
@barieom - Thanks! Looks good now. Is this ready to merge?

**Comment by barieom** [comment]
> @barieom - Thanks! Looks good now. Is this ready to merge?

@brett0000FF - yes it is!

**Pull request merged**
