### PR TITLE
Add AWS-SDK-Go-v2 and migrate to pkg.go.dev

### PR DESCRIPTION
**Pull request by MaerF0x0**
### What does this PR do?
* APM seems to have aws-sdk-go-v2 compatibility, adds docs to it. 
* moves from godoc.org -> pkg.go.dev
### Motivation
yololol (I was learning about the APM and saw an opportunity to contribute) 

### Additional Notes

---

### Reviewer checklist
- [] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by MaerF0x0** [comment]
@katiehockman  -> do you mind please getting the right eyes on this?

**Comment by maycmlee** [comment]
Thanks @MaerF0x0 for opening this PR! We will review and be back in touch.

**Review by katiehockman — APPROVED** [review]
Oh awesome!! Thanks for doing this @MaerF0x0  😄

**Review by kayayarai — APPROVED** [review]
Thanks for the update! The updates to the FR and JA files might get overwritten by our translation process, but the fixes will go through the translation pipeline and get back in eventually.

**Pull request merged**
