### PR TITLE
add note that heapster must be running in standalone mode

### PR DESCRIPTION
**Pull request by irabinovitch**
add note that heapster must be running in standalone mode

### CODE REVIEW

**Comment by jyee** [comment]
Is there a better link to stand alone docs? The link to the repo doesn't seem as helpful as it ought to be.

Maybe this documentation? https://github.com/vishh/heapster-1/blob/master/docs/standalone.md
it's a fork of the main heapster repo, but it looks like the current master for heapster no longer includes those docs.

**Comment by jyee** [comment]
Or I guess we could link to https://github.com/kubernetes/heapster/blob/heapster-old/docs/standalone.md (old branch)

**Comment by technovangelist** [comment]
hmm, 2 months. Any updates needed or are we good to go @jyee @irabinovitch

**Comment by irabinovitch** [comment]
I haven't found a better repo / docs to link to.

**Pull request merged**
