### PR TITLE
update postman collection

### PR DESCRIPTION
**Pull request by ian28223**
### What does this PR do?

- Updates the collection variable from `dd_api_key` to the new `datadog_api_key`
- Updates the collection variable from `dd_app_key` to the new `datadog_application_key`
- Renamed everything that actually needs user input/change from a `{postman_variable_format}` to `<INSERT_SOMETHING_HERE>`

### Motivation

- I imported the newest collection and found that some requests failed because of missing variables e.g. `{comment_id}`. It was not evident the `{this}` is something that I would need to change because they looked like variables rather than something I need to manually change.

### Preview link

No UI change. 
https://docs-staging.datadoghq.com/ian.bucad/update_postman_collection/developers/guide/using-postman-with-datadog-apis/#import-the-datadog-collection

For example, for branch "lucas/update-dotnet-tracing" that updates the docs in path "https://docs.datadoghq.com/tracing/languages/dotnet/", this is the preview link:
https://docs-staging.datadoghq.com/lucas/update-dotnet-tracing/tracing/languages/dotnet/
-->

### Additional Notes

- the format `<NEEDS_USER_INPUT>` is just something we already use in some of the request Body. I think we should make this as a convention and communicate it our docs/faqs to let the user know that if the see something `<ENCLOSED_LIKE_THIS>`, then they should change it. For things in `{postman_variable_format}`, then those they need to change in scripts and/or collection, environment, or global variables.

### CODE REVIEW

**Comment by l0k0ms** [comment]
Hello Ian, many thanks for this PR. The format `<PLACEHOLDER>` is documented in our contributing guidelines: https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#conventions and enforced across our documentation.

I removed an outdated collection file (tbh idk how it ended up there) the true one is the one in the resources folder.

Regarding your point i think you are right (for the placeholders if the param is in the path) i think i thought i would be able to script all variables to get them automatically.

**Comment by l0k0ms** [comment]
Hello Ian, many thanks for this PR. The format `<PLACEHOLDER>` is documented in our contributing guidelines: https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#conventions and enforced across our documentation.

I removed an outdated collection file (tbh idk how it ended up there) the true one is the one in the resources folder.

Regarding your point i think you are right (for the placeholders if the param is in the path) i think i thought i would be able to script all variables to get them automatically.

**Comment by ian28223** [comment]
aha.. thanks!
It would be great to have that `<PLACEHOLDER>` format mentioned somewhere in 
https://docs.datadoghq.com/developers/guide/using-postman-with-datadog-apis/
probably next time a make PR

**Comment by l0k0ms** [comment]
🤔 that's a good idea, let me create a card for this.

**Pull request merged**
