### PR TITLE
[OPB-583] Remove outdated Agent <> OP guide

### PR DESCRIPTION
**Pull request by binarylogic**
### What does this PR do?

This removes a doc that is outdated with the launch of the Observability Pipelines Worker. The entire doc is no longer relevant and the tutorial does not work. @silversupreme is working on a Datadog reference architecture guide that will replace this with the new OP Worker.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by maycmlee** [comment]
Hi @binarylogic, when we remove a page we usually redirect it to another page, so that users who have bookmarked the link don't get a 404. Which doc page should this be redirected to? I'll also need to remove it from the nav and remove any links to this page, is okay if I make a commit to your branch?

**Comment by binarylogic** [comment]
Hey @maycmlee sure, go for it. I do not have a page to link to. We will be replacing it this quarter with the new Datadog architecture guide, but we don't have that yet. I'm removing it because the entire page and approach is outdated. All of the tutorials are broken as well.

**Comment by maycmlee** [comment]
Added aliases to the Installation page for now and removed links to the deleted doc. Created [DOCS-4903](https://datadoghq.atlassian.net/browse/DOCS-4903) to move aliases to the new Datadog architecture doc once it's available.

Preview link: https://docs-staging.datadoghq.com/may/preview-binarylogic-remove-doc/observability_pipelines/production_deployment_overview/

**Comment by maycmlee** [comment]
@binarylogic is this good to merge? or are we still waiting for a review from @silversupreme?

**Comment by maycmlee** [comment]
Chatted with Ari about this and he's reviewed and is good with it being removed.

**Review by maycmlee — APPROVED** [review]

**Pull request merged**
