### PR TITLE
Removing ruby code snippet from the Datadog extension tab for custom metrics

### PR DESCRIPTION
**Pull request by SiddhithaBhoopathy**
### What does this PR do?
Related to this PR: https://github.com/DataDog/documentation/pull/19080, we also have this section explaining custom metrics to be sent for Ruby via extension.

### Motivation
Customer opened an escalation. [SLES-1256 Unable to send custom metric with ruby](https://datadoghq.atlassian.net/browse/SLES-1256?atlOrigin=eyJpIjoiOGQ1NDIzZDA0MzY1NGIxZDllZGJhZTdmOTViNjdmMWYiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by buraizu — CHANGES_REQUESTED** [review]
Thanks for the PR, but `ruby` also needs to be removed from the `programming-lang-wrapper` on line `63`, or it remains an option on the page and causes unexpected behavior.

**Comment by buraizu** [comment]
Not sure why, but updating the code lang wrapper did not trigger a new GitLab build, and it's marked as `skipped`. Merging in the `master` branch as a possible resolution as mentioned in this [GitLab issue](https://gitlab.com/gitlab-org/gitlab/-/issues/217129)

**Comment by SiddhithaBhoopathy** [comment]
Hey @buraizu Apologies I missed the notification, thank you for making the changes.
Not sure of the process here, we have an internal slack channel for documentation changes approval, should I reach out there?

**Comment by buraizu** [comment]
Hi @SiddhithaBhoopathy, apologies for the confusion -- I realize now that the preview branch didn't build for this PR because the branch name excludes a `/`. For any future PRs to the documentation repo, you can title your branch something like <your_name>/<branch_name>` and a preview branch for your changes is automatically created.
No worries this time though -- I was able to confirm this seems to be working as expected on a local build.

**Review by buraizu — APPROVED** [review]

**Pull request merged**
