### PR TITLE
Update with Link to Event Processing Pipeline in app based on customer feedback

### PR DESCRIPTION
**Pull request by Aziraphale81**
### What does this PR do?
Add a link to Enrich & Normalize tab of Event Processing as a call to action.

### Motivation
Customer provided feedback that it was not clear where event processing pipelines should be added and configured. The links to log pipelines led them to attempt to create their desired event parsing in log pipelines instead. Hopefully this saves others from similar issues.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by Aziraphale81** [comment]
I (hopefully) corrected the app link for newly added link [21]

**Review by rtrieu — CHANGES_REQUESTED** [review]
Hi @Aziraphale81, as a rule, we don't make promises of supporting things in the future. Other than that, the update looks great. Thank you!

**Comment by Aziraphale81** [comment]
The promise surprised me too, it was already in but I like the omission. Changes committed :)

**Review by rtrieu — APPROVED** [review]
LGTM!

**Pull request merged**
