### PR TITLE
Advanced instrumentation 2.0

### PR DESCRIPTION
**Pull request by l0k0ms**
### What does this PR do?
This PR aims to break down this single page: https://docs.datadoghq.com/tracing/advanced_usage/
into several one within the same section.

New pages will follow the H2 logic. 

### Motivation
It was getting out of haaaaaand.

### Additional Notes
No new content is created in this PR, and this PR should be merged after this one: 
https://github.com/DataDog/documentation/pull/3989

Some pages logic have been changed to benefit from the tab and anchor logic: 

* Custom Tagging 
* Correlate Traces and logs

### Preview link

- [ ] [Advanced usage main page](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/)
- [ ] [Custom Tagging](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/custom_tagging/?tab=java)
- [ ] [Change Agent hostname](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/change_agent_hostname/?tab=java)
- [ ] [Manual instrumentation](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/manual_instrumentation/?tab=java)
- [ ] [Open Tracing](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/opentracing/?tab=java)
- [ ] [Distributed Tracing](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/distributed_tracing/?tab=java)
- [ ] [Priority Sampling](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/priority_sampling/?tab=java)
- [ ] [Correlate Traces and logs](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/correlate_traces_and_logs/?tab=java)
- [ ] [Debugging](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/debugging/?tab=java)
- [ ] [Security](https://docs-staging.datadoghq.com/gus/advanced-instrumentation-2.0/tracing/advanced_usage/security/)

### CODE REVIEW

**Comment by tylerbenson** [comment]
FYI, this will probably conflict with #3989.

**Comment by l0k0ms** [comment]
@tylerbenson it will :) but keep on going with #3989 I will do the conflict merges.

**Comment by tylerbenson** [comment]
I'm not sure exactly when it will be ready to merge.  If you want to merge yours first, feel free to rebase mine.  😺

**Comment by l0k0ms** [comment]
noted 😈

**Pull request closed without merging**
