### PR TITLE
[CLOUDCRAFT-222] Using the Bits menu

### PR DESCRIPTION
**Pull request by jamesponddotco**
### What does this PR do? What is the motivation?
Add an article to the Cloudcraft documentation on how to use the Bits menu.

### Merge instructions
Please wait until the Cloudcraft team has reviewed the content before going ahead with the review and merging of the article.

- [x] Please merge after reviewing

### CODE REVIEW

**Review by aliciascott — APPROVED** [review]
Hi @jamesponddotco looks great! I went ahead and added some changes directly to the branch - updated the index file so it shows on the getting started menu, and re-worded some things , let me know if you had any questions and when you are ready to have this merged.

**Comment by jamesponddotco** [comment]
Thanks, @aliciascott! Just waiting for a content review by @srividya-rajagopalan and then we can merge. I'll let you know when that happens.

**Comment by aliciascott** [comment]
> Thanks, @aliciascott! Just waiting for a content review by @srividya-rajagopalan and then we can merge. I'll let you know when that happens.

Sounds good! I pushed one more commit, for the last callout box, for something like that we'd typically just use a **Note** to indicate something needs to be done to use the given feature.

**Review by srividya-rajagopalan — APPROVED** [review]

**Comment by jamesponddotco** [comment]
@aliciascott Seems like we got content approval, so you can proceed :)

**Pull request merged**
