### PR TITLE
Update dotnet.md

### PR DESCRIPTION
**Pull request by johannbotha**
Updating Dog net based on Igor's recommendation https://dd.slack.com/archives/C072SJJM3D1/p1733342114505629

### CODE REVIEW

**Review by michaelcretzman — APPROVED** [review]

**Comment by michaelcretzman** [comment]
Approved.
You can merge your PR by adding a comment containing `/merge`.
The PR will go into the merge queue automatically once it's approved.

**Review by kr-igor — APPROVED** [review]

**Comment by johannbotha** [comment]
`/merge`

/merge

**Review by janewang-datadog — APPROVED** [review]

**Review by janewang-datadog — CHANGES_REQUESTED** [review]
update the library name in addition to the link 

[**IBM.Data.DB2.Core**](https://www.nuget.org/packages/IBMMQDotnetClient)

**Comment by johannbotha** [comment]
> update the library name in addition to the link
> 
> [**IBM.Data.DB2.Core**](https://www.nuget.org/packages/IBMMQDotnetClient)

The library is called that already. Am I missing something

image

**Comment by johannbotha** [comment]
> update the library name in addition to the link
> 
> [**IBM.Data.DB2.Core**](https://www.nuget.org/packages/IBMMQDotnetClient)

Update to `IBMMQDotnetClient`

**Review by janewang-datadog — APPROVED** [review]

**Pull request closed without merging**
