### PR TITLE
Update RUM integration information for next version of the framework

### PR DESCRIPTION
**Pull request by nachoBonafonte**
### What does this PR do?
Update RUM integration information for next version of the framework

### Motivation
Next version of the framework includes an improved integration with RUM product

### Preview

https://docs-staging.datadoghq.com/nachoBonafonte/new-RUM-integration/continuous_integration/setup_tests/swift
https://docs-staging.datadoghq.com/nachoBonafonte/new-RUM-integration/continuous_integration/guides/rum_swift_integration
https://docs.datadoghq.com/nachoBonafonte/new-RUM-integration/continuous_integration/guides

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by maycmlee** [comment]
Hey @nachoBonafonte ! I merged master into the branch to try to fix the build_preview

**Review by maycmlee — APPROVED** [review]

**Comment by maycmlee** [comment]
Hey @nachoBonafonte, should I go ahead and merge this?

**Comment by nachoBonafonte** [comment]
Yes please

**Comment by nachoBonafonte** [comment]
Yes @maycmlee, please

**Pull request merged**
