### PR TITLE
Update marathon integration docs to include ACS token auth

### PR DESCRIPTION
**Pull request by jkorzekwa-atlassian**
Updating the marathon integration documentation to reflect the changes in the https://github.com/DataDog/dd-agent/pull/3037 pull request

### CODE REVIEW

**Comment by irabinovitch** [comment]
@jkorzekwa-atlassian Thanks! We'll hold on merging this until the agent pr is merged. I appreciate the completeness of the PR!

**Comment by technovangelist** [comment]
@jkorzekwa-atlassian looks like there are some changes requested on the agent pr. Update those and then when that is merged we can merge this. Thanks

**Comment by jkorzekwa-atlassian** [comment]
Hi @technovangelist, I made those changes back in December. Did I not submit something for review correctly? Sorry, I am not used to using github :)

**Comment by technovangelist** [comment]
Checked with the devs. You are right. all is good on your end just waiting on some testing. thanks.

**Comment by technovangelist** [comment]
Looks like its all merged and good to go. Thanks for updating this.

**Pull request merged**
