### PR TITLE
E wachnowezki/ga dynamic instrumentation

### PR DESCRIPTION
**Pull request by EWachnowezki**
### What does this PR do? What is the motivation?

Bring dynamic instrumentation documentation to GA state.

### Merge instructions

We would like to merge around re:invent - until then there is also more content that will be added

### CODE REVIEW

**Comment by kayayarai** [comment]
Hi @EWachnowezki . I gave this a first pass, please check I didn't mess anything up. 

Looks like the Data Scrubber topic is still missing some instructions about default config and customizing it. Are you still working on that? 

Also, is Java the only lang for which the version is going up? And do we want to update that version number in line 47 of content/en/dynamic_instrumentation/_index.md too?

**Comment by EWachnowezki** [comment]
Thanks for taking a look - indeed its for all languages - so let me remove the beta tags there as well - i am also waiting for @OmerRaviv to merge his changes.

**Review by kayayarai — APPROVED** [review]
Looking good! Let me know when you've taken a last look and are ready to ship

**Comment by OmerRaviv** [comment]
Thanks so much for your edits @kayayarai ! This all LGTM but I'll let @EWachnowezki respond to your question.

**Comment by EWachnowezki** [comment]
So for me - we are good to go :)

**Pull request merged**
