### PR TITLE
Guide for using colors (ready to review)

### PR DESCRIPTION
**Pull request by omar-nema**
Needed to support release of new categorical colors feature

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by urseberry** [comment]
I added the WIP label to remove this from the docs team on-call queue. Please remove the label when you are ready for the documentation team to review the PR.

**Comment by omar-nema** [comment]
Thank you @urseberry - appreciate that.

**Comment by omar-nema** [comment]
Ready for review!

**Comment by cswatt** [comment]
Added DOCS-4183 for review

**Pull request merged**
