### PR TITLE
Add known flaky failed tests to the docs

### PR DESCRIPTION
**Pull request by liashenko**
### What does this PR do?

Adding information about known flaky failed tests to the docs.

### Motivation

We've recently added a new feature in CI Visibility to calculate and display known flaky failed tests.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by buraizu — CHANGES_REQUESTED** [review]
Thanks, left a few minor suggestions. For context around the changes to the alt text, we have an internal wiki containing alt text guidelines that you can access by searching "Writing alt text" in our internal docs.
Also, just wanted to confirm that the screenshot is accurate and up-to-date. I wasn't able to find the `Commits` tab when going to the `Tests` page and using the `Branches` view, as mentioned. Customers can sometimes open support tickets when images in the documentation do not match the UI, so perhaps either the image or the instructions could be updated? Or perhaps this is simply a limitation of the data available in the Demo account. Thanks in advance for any clarification!

**Comment by liashenko** [comment]
@buraizu hey, thanks for feedback! So when you go to the Tests page, select the Branches view, click on a row a test commit page opens. I think maybe I should rephrase a bit.

**Review by buraizu — COMMENTED** [review]
@liashenko thanks for confirming, the updated screenshot seems fine! With that said, I noticed that the `link_checks_preview` is not passing in GitLab. Would you be able to merge in the latest `master` branch and push up once again? Apologies if that's inconvenient or otherwise not feasible -- if so, I can follow up with my team about whether this check is critical under these circumstances.

**Comment by liashenko** [comment]
@buraizu done!

Now I get this error:
```
[Check failure on line 283 in content/fr/serverless/configuration/_index.md](https://github.com/DataDog/documentation/commit/8a43fc3c472cd784afa7678898b77d535eac7fb0#annotation_4282665242) 
Use only one space between words and sentences (not two).
```
But it's not related to my changes.

**Review by buraizu — APPROVED** [review]

**Comment by buraizu** [comment]
Thanks again!  From what I can tell everything looks fine in GitLab now, and I'm fairly certain that error can be ignored.

**Pull request merged**
