### PR TITLE
[apm/go] Add Go docs

### PR DESCRIPTION
**Pull request by palazzem**
### What does this PR do?

Updates Go docs with the new style.

### Motivation

Makes the Go docs easier to read.

### Preview link

Pages that have been changed:

* https://docs-staging.datadoghq.com/palazzem/go-docs-restyle/tracing/setup/go/
* https://docs-staging.datadoghq.com/palazzem/go-docs-restyle/tracing/advanced_usage/custom_tagging/?tab=go
* https://docs-staging.datadoghq.com/palazzem/go-docs-restyle/tracing/advanced_usage/distributed_tracing/?tab=go
* https://docs-staging.datadoghq.com/palazzem/go-docs-restyle/tracing/advanced_usage/open_tracing/?tab=go
* https://docs-staging.datadoghq.com/palazzem/go-docs-restyle/tracing/advanced_usage/priority_sampling/?tab=go
* https://docs-staging.datadoghq.com/palazzem/go-docs-restyle/tracing/advanced_usage/logging/?tab=go
* https://docs-staging.datadoghq.com/palazzem/go-docs-restyle/tracing/advanced_usage/debugging/?tab=go

### Additional Notes

None.

### CODE REVIEW

**Comment by dd-caleb** [comment]
Open tracing also didn't compile, this fixes it:

```go

package main

import (
	"github.com/opentracing/opentracing-go"

	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func main() {
	// Start the regular tracer and return it as an opentracing.Tracer interface. You
	// may use the same set of options as you normally would with the Datadog tracer.
	t := opentracer.New(tracer.WithServiceName("my-service"))

	// Stop it using the regular Stop call for the tracer package.
	defer tracer.Stop()

	// Set the global OpenTracing tracer.
	opentracing.SetGlobalTracer(t)

	// Use the OpenTracing API as usual.
}


```

**Comment by dd-caleb** [comment]
advanced usage / logging, should use `:=`:

```go

package main

import (
	"net/http"

	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func handler(w http.ResponseWriter, r *http.Request) {
	// Create a span for a web request at the /posts URL.
	span := tracer.StartSpan("web.request", tracer.ResourceName("/posts"))
	defer span.Finish()

	// Retrieve Trace ID and Span ID
	traceID := span.Context().TraceID()
	spanID := span.Context().SpanID()
}


```

**Comment by dd-caleb** [comment]
I think that's it

**Comment by palazzem** [comment]
Thanks! Updating the code immediately!

**Pull request merged**
