### PR TITLE
Update OpenTelemetry custom instrumentation documentation

### PR DESCRIPTION
**Pull request by PerfectSlayer**
### What does this PR do? What is the motivation?

This PR updates the custom instrumentation samples using Java Tracer and OpenTelemetry.
The feature is still in Beta and gets improved over time, meaning we need to update the samples too.

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by aliciascott — APPROVED** [review]
Looks good! @PerfectSlayer did you want us to go ahead and merge this as well ?

**Comment by PerfectSlayer** [comment]
Hey @aliciascott 👋 
Not yet, the documented change will be shipped first week next year. 
I can ping you or your team to get it merged then :)

**Comment by schmidt-galen-heb** [comment]
Friendly bump on this, we've upgraded to the latest `dd-java-agenti` and I was confused why `datadog-root-span-key` wasn't working 🙂

**Comment by PerfectSlayer** [comment]
Sorry @schmidt-galen-heb, I forgot to ask for merging the PR.
That's great you were able to find this PR and sorry for the trouble 🙇 

Hey @aliciascott Can you merge it then? 🙏

**Pull request merged**
