### PR TITLE
Added a search bar to integrations page

### PR DESCRIPTION
**Pull request by amalik12**
### What does this PR do?

This adds a search bar to the integrations page. The search currently filters based on the `name` and `public_name` fields for each integration:

### Motivation

A search bar would help a user get to an integration page as quickly as possible if they already know which page they want to view. It's currently very time consuming to scroll through 200+ tiles to find a specific integration, and it's difficult to determine the current alphabetical order position you're looking at based on logos alone.

### Preview link

https://docs-staging.datadoghq.com/adisa/integrations-search/integrations/

### CODE REVIEW

**Comment by mstbbs** [comment]
@amalik12 - this is really cool! Some of the styles didn't make it to preview though, see attached.
screen shot 2018-05-03 at 2 54 46 pm

**Comment by amalik12** [comment]
Oops, I'll undo my commits.

**Comment by amalik12** [comment]
Ok, done

**Comment by l0k0ms** [comment]
looks good to me 👌

**Comment by mstbbs** [comment]
G2G!

**Pull request merged**
