### PR TITLE
Add IP allowlist stipulation about API key access

### PR DESCRIPTION
**Pull request by sophiah123**
### What does this PR do?

Adds that it needs user-generated API key, it cannot generate an API key itself under the IP allowlist

### Motivation

https://datadoghq.atlassian.net/browse/ACCESS-1604
Comment from Marketplace/Integration PMs

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by drichards-87 — APPROVED** [review]

**Comment by sophiah123** [comment]
Hi @anawishnoff and @srosenthal-dd , is this language better? Help with the copy is appreciated!

**Comment by srosenthal-dd** [comment]
Current version seems fine to me!

**Review by anawishnoff — APPROVED** [review]

**Comment by drichards-87** [comment]
@sophiah123 Is this ready to be merged?

**Comment by sophiah123** [comment]
@drichards-87 , yes this is ready to merge! Thanks!

**Pull request merged**
