### PR TITLE
Anthony.bravo/colab 1262/zendesk rum app pic

### PR DESCRIPTION
**Pull request by abravo3641**
### What does this PR do? What is the motivation?

Picture / gif assets that will be used for app documentation

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Review by ryanpeffers — APPROVED** [review]

**Comment by hestonhoffman** [comment]
Hi @abravo3641, we don't use GIFs on the docs site for accessibility reasons. Could you replace these with mp4s?

**Review by hestonhoffman — CHANGES_REQUESTED** [review]
Hi @abravo3641, we don't use GIFs on the docs site for accessibility reasons. Could you replace these with mp4s?

**Comment by abravo3641** [comment]
> Hi @abravo3641, we don't use GIFs on the docs site for accessibility reasons. Could you replace these with mp4s?

Hello @hestonhoffman, we are not planning to use these in the datadog documentation but instead on a zendesk marketplace app that we are building. I don't think their markdown processor supports linking video files, would you happen to know the best place to place these? Eg. documentation pics for apps outside datadog?

**Comment by hestonhoffman** [comment]
> > Hi @abravo3641, we don't use GIFs on the docs site for accessibility reasons. Could you replace these with mp4s?
> 
> Hello @hestonhoffman, we are not planning to use these in the datadog documentation but instead on a zendesk marketplace app that we are building. I don't think their markdown processor supports linking video files, would you happen to know the best place to place these? Eg. documentation pics for apps outside datadog?

I see. This repo is specifically for our official documentation site. Images added that are not linked somewhere on the docs website are probably going to be removed by automation tools - we're actually working on one of these now. Could you perhaps source these images from an s3 bucket instead?

**Comment by hestonhoffman** [comment]
I've closed this, as we can't use the docs repo to store assets that are not used on the docs website.

**Pull request closed without merging**
