### PR TITLE
[widgets docs] Update time settings to use new format

### PR DESCRIPTION
**Pull request by MLaureB**
### What does this PR do?

Updates screenboard widgets documentation to use new time format instead of the old one.

Old format:
`"timeframe": "1h"`

New format:
`"time": {"live_span": "1h"}`

### Motivation

We're in the process of adding global time selector to screenboards and we need a better time format to support this feature.

### Preview link

https://docs-staging.datadoghq.com/marielaure.bardonnet/screenboard_widget_new_time_format/graphing/dashboards/widgets/

### Additional Notes

This PR is still in progress. We're still working on converting all existing screenboards to use this new time format instead of the old one.

### CODE REVIEW

**Comment by jeremy-lq** [comment]
@MLaureB Thanks for the doc update! Let us know when this is ready to merge.

**Comment by MLaureB** [comment]
Will do! 
I'm currently in the process of migrating all the screenboards to use this new time format.
Should be done by the end of the day (or tomorrow) and then I'll be ready to merge this PR.

**Comment by iddl** [comment]
Not necessary but nice to do https://github.com/DataDog/documentation/blob/master/static/sh/agentcountscreenboard.sh

**Comment by MLaureB** [comment]
Nice! Didn't see this file when I created the PR (will check if any new file like this has been added).

**Comment by MLaureB** [comment]
@jeremy-lq this is now ready to be merged!

**Pull request merged**
