### PR TITLE
Add `cdk-datadog-resources` to libraries page

### PR DESCRIPTION
**Pull request by NomadBlacky**
### What does this PR do?

Add [cdk-datadog-resources](https://github.com/NomadBlacky/cdk-datadog-resources) to libraries page.

### Motivation

cdk-datadog-resources manages Monitor etc. with AWS CDK.

### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by jeremy-lq** [comment]
@NomadBlacky, I was referring to https://github.com/NomadBlacky/cdk-datadog-resources/issues/27 https://github.com/NomadBlacky/cdk-datadog-resources/issues/26 https://github.com/NomadBlacky/cdk-datadog-resources/issues/24 which look to be open items for the repo

**Comment by NomadBlacky** [comment]
@jeremy-lq I understand, thank you!
I will resolve those in the near future.

**Comment by phrawzty** [comment]
Hello! I've opened a PR to get those issues resolved: https://github.com/NomadBlacky/cdk-datadog-resources/pull/85
Please let me know if there's anything more I can do to help. 👍

**Comment by apigirl** [comment]
Hi @nomadblacky, your fork unfortunately got caught in the middle of a data purge that we had to do on the repo for security purposes. Then I got a little bit overzealous in cleaning it up. Working on a fix for it now!

**Comment by apigirl** [comment]
Hi @nomadblacky, your fork unfortunately got caught in the middle of a data purge that we had to do on the repo for security purposes. Then I got a little bit overzealous in cleaning it up. Working on a fix for it now!

**Comment by apigirl** [comment]
@NomadBlacky - I've added the info back in here - https://github.com/DataDog/documentation/pull/10934. Once we can get https://github.com/NomadBlacky/cdk-datadog-resources/pull/85 merged, we can merge here!

**Pull request closed without merging**
