### PR TITLE
Updated Trace ID Injection Docs

### PR DESCRIPTION
**Pull request by andrewsouthard1**
### What does this PR do?

This PR updates the Trace ID Log Injection documentation, and updates the links in the logging docs to fit the new title 

### Motivation

We are releasing this feature GA.

### Preview link

"https://docs.datadoghq.com/tracing/advanced_usage/#logging", this is the preview link:
https://docs-staging.datadoghq.com/andrew/traceidlog-update/tracing/advanced_usage/#correlate-traces-and-logs

"https://docs.datadoghq.com/logs/log_collection/ruby/" this is the preview link:
https://docs-staging.datadoghq.com/andrew/traceidlog-update/logs/log_collection/ruby/

"https://docs.datadoghq.com/logs/log_collection/java/" this is the preview link:
https://docs-staging.datadoghq.com/andrew/traceidlog-update/logs/log_collection/java/

"https://docs.datadoghq.com/logs/log_collection/nodejs/" this is the preview link:
https://docs-staging.datadoghq.com/andrew/traceidlog-update/logs/log_collection/nodejs/

"https://docs.datadoghq.com/logs/log_collection/python/" this is the preview link:
https://docs-staging.datadoghq.com/andrew/traceidlog-update/logs/log_collection/python/
-->

### Additional Notes

The title has been updated in this section from `#logging` to `#correlate-traces-and-logs` and the nav bar on the left hand side needs to be updated to reflect this. I have already gone ahead and updated the logging docs in this PR to include this new link `tracing/advanced_usage/#correlate-traces-and-logs`

### CODE REVIEW

**Comment by NBParis** [comment]
@andrewsouthard1 I don't think we should use the word `correlate` because there is no impact from the traces to the logs or whatsoever.

To bring the definition back:

```
have a mutual relationship or connection, in which one thing affects or depends on another.
```

I would tend to say `Link` might be more meaningful.

**Comment by rochdev** [comment]
@NBParis I think correlate is the right word.

This is what I could find (and how I've always noticed it being used):

```
a mutual relationship or connection between two or more things
```

**Comment by andrewsouthard1** [comment]
Yeah we want to go with correlate here, "correlating an id" is a common phrase.

**Comment by rochdev** [comment]
@andrewsouthard1 About all the changes from `IDs` to `ID`, the idea is that the span ID is also a trace identifier. So eventually we will correlate with 2 different IDs. Should we say that differently?

**Comment by andrewsouthard1** [comment]
> @andrewsouthard1 About all the changes from `IDs` to `ID`, the idea is that the span ID is also a trace identifier. So eventually we will correlate with 2 different IDs. Should we say that differently?

@rochdev That's a good point but I think it's a cleaner look without the `S`s, and grammatically you can say they're both a Trace Identifier and it still adds up.

**Pull request merged**
