### PR TITLE
[WEB-29] Japanese typography update

### PR DESCRIPTION
**Pull request by davidejones**
### What does this PR do?

Updating ja typography

### Motivation

Prepare GA release of the Japanese version of the documentation

### Preview link
https://docs-staging.datadoghq.com/david.jones/jp-typography/ja/agent/basic_agent_usage/amazonlinux/?tab=agentv6v7

### CODE REVIEW

**Comment by l0k0ms** [comment]
Latin chars in tables are too big it seems: https://docs-staging.datadoghq.com/david.jones/jp-typography/ja/agent/basic_agent_usage/#agent-%E3%82%A2%E3%83%BC%E3%82%AD%E3%83%86%E3%82%AF%E3%83%81%E3%83%A3

**Comment by jiboong** [comment]
good to go from my perspective!

**Comment by l0k0ms** [comment]
@jiboong i think the text when overing an integration tile is too big: https://a.cl.ly/P8uRRzn2
https://docs-staging.datadoghq.com/david.jones/jp-typography/ja/integrations/

**Comment by sarina-dd** [comment]
+1 to replicating the big text for integration tiles. Also the video on the APM page isn't loading, so it leaves a giant gap at the top of the page.

**Pull request merged**
