### PR TITLE
Improvements to APM -> Compatibility -> .NET Core

### PR DESCRIPTION
**Pull request by zacharycmontoya**
### What does this PR do?
Adds a new section in the .NET Core compatibility docs to highlight known runtime issues that affect Datadog automatic instrumentation.

### Motivation
We discovered another issue that with an older version of .NET Core 2.0

### Preview
https://docs-staging.datadoghq.com/zach.montoya/net-core-2.0.0/tracing/compatibility_requirements/dotnet-core/

### Additional Notes
N/A

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by andrewardito — APPROVED** [review]
I love this.

**Review by sarina-dd — APPROVED** [review]

**Comment by zacharycmontoya** [comment]
Sorry for the inactivity on this, I was still working through some feedback from the engineering team. Until I finalize that, I will keep this as a draft and re-request approvals if things change.

**Review by lucaspimentel — APPROVED** [review]
Thanks!

**Review by andrewardito — APPROVED** [review]
LGTM!

**Review by jaycdave88 — APPROVED** [review]

**Pull request merged**
