### PR TITLE
APM (Tracing) New Layout

### PR DESCRIPTION
**Pull request by l0k0ms**
### What does this PR do?

This PR aims to reduce the perceived complexity of APM setup

The main idea is we split the `APM Setup` section in two:

* `Basic`: minimum required information per language in order to be easy to understand for begginers 
* `Advanced`: Advanced configuration for experimented user that need less context and can understand small code snippets

We then factorise everything that is a concept in the `Getting further` section and everything related to the UI in the `APM UI` section
New layout should be:

**APM (Tracing)**
**| - Setup (Basic)**
| - - Docker
| - - Kubernetes
| - - Java 
| - - Python
| - - Ruby
| - - Go
| - - NodeJS
| - - .NEt
| - - Php

**| - Setup (Advanced)**
| - - Manual Tracing 
| - - Custom Tagging
| - -  Distributed Tracing
| - -  OpenTracing
| - -  Sampling
| - -  Debugging

**| - APM UI**
| - - Services List
| - - Service page
| - - Resource page
| - - Trace page
| - - Trace Search
| - - Trace Analytics

**| - Getting further**
| - - First Class Dimensions
| - - Apdex
| - - Resource Monitor
| - - Service Monitor
| - - APM in Dashboard
| - - Trace metrics namespace
| - - Storage & Sampling
| - - APM events

**| - Trace API**
**| - Librairies**
**| - Security**

For the Setup (basic) :

Home page should include information regarding: 

* Setup process
* Agent configuration
* Scrubbing sensitive information

Each page is focused on a language and each page should include the following sections: 

* Installation
* Quick Start
* Compatibility
* Performance
* Configuration

For advanced Setup we want to describe the feature and then do a "per language" code snippet as used here: 
https://docs.datadoghq.com/ja/guides/metrics/#setup

### Preview link

* https://docs-staging.datadoghq.com/gus/tracing-new-layout/tracing/

### Open questions

* Should we add other section to basic/advanced setup?
* Should advanced setup be only one single page?

### CODE REVIEW

**Comment by phrawzty** [comment]
So I'm going to complicate the matter further, haha. There is significant content duplication between these docs and those in http://pypi.datadoghq.com/trace/docs/ (built from [this](https://github.com/DataDog/dd-trace-py) and soon to be migrated to RTD, apparently). I wonder if there might be a sane way to consolidate these two things.

Broadly, there are three ways we could do this:
1. Move *all* docs to the [dd-trace-py repo](https://github.com/DataDog/dd-trace-py/tree/master/docs) and import / build from there.
1. Move *all* docs to the Datadog Documentation repo, then just reference those docs from the dd-trace-py README (or whatever).
1. Consolidate some docs in the Datadag Dogs repo, and maintain some in the dd-trace-py repo, and cross-reference between the two.

In the latter "mixed" option, a potential split might be to move Installation, Getting Started, Instrumentation, Sampling, and Trace Filtering to the Datadog Docs, and leave API and the rest in the dd-trace-py repo.

Thoughts?

**Comment by delner** [comment]
@l0k0ms Opened up #3025 which implements Ruby APM in this new layout. I'd like to merge it into this PR.

**Comment by iFallUpHill** [comment]
The preview link didn't seem to update with the latest changes from my push.

**Comment by l0k0ms** [comment]
@iFallUpHill github had issues. The preview should be updated now

**Comment by rachelaskin** [comment]
This might be minor, but do y'all think it would be beneficial to add "(Coming soon)" to .NET and PHP as highlighted in the below screenshot? I see that we note that those languages aren't yet available on the left menu, but as the in-doc list is for "supported languages," it might help to be specific within the doc.

image

**Pull request merged**
