### PR TITLE
connect_dbm_and_apm: fix dbmPropagationMode

### PR DESCRIPTION
**Pull request by ikonst**
### What does this PR do? What is the motivation?
Correct where `dbmPropagationMode` is assigned.

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Comment by drichards-87** [comment]
Thanks for submitting this PR! Someone on our team will take a look at this shortly (DOCS-7245).

**Comment by ikonst** [comment]
I'd like to make sure this change is correct -- contrast with https://github.com/DataDog/dd-trace-js/pull/2480 where it was implemented for Node — cc @rochdev @tlhunter 

In particular, `packages/datadog-plugin-pg/test/index.spec.js` does:
https://github.com/DataDog/dd-trace-js/blob/9e7b3baef8b0b23efb2af8465c617267c0757bce/packages/datadog-plugin-pg/test/index.spec.js#L455-L458
```js
          tracer.init()
          tracer.use('pg', {
            dbmPropagationMode: 'full'
          })
```

but `index.d.ts` has it in `TraceOptions`:
https://github.com/DataDog/dd-trace-js/blob/9e7b3baef8b0b23efb2af8465c617267c0757bce/index.d.ts#L518-L522

**Comment by rochdev** [comment]
> I'd like to make sure this change is correct
The change is correct, it's the type definitions that are incorrect.

**Comment by rochdev** [comment]
Actually, both are supported, although the previous version doesn't seem to be documented. This is because this can be either configured globally or per integration.

**Review by lu-zhengda — APPROVED** [review]

**Review by jhgilbert — APPROVED** [review]

**Pull request merged**
