### PR TITLE
Improve Example for DD_TRACE_HEADER_TAGS

### PR DESCRIPTION
**Pull request by brett0000FF**
### What does this PR do? What is the motivation?

https://datadoghq.atlassian.net/browse/DOCS-6163
* Originally merged updates per this Jira card.
* Per Vidur Khanna, the examples still lacked explanation and more specificity.

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Comment by brett0000FF** [comment]
Whoever looks at this from APM .NET Tracer team, please let me know if you can think of better examples to put here. Thanks!

**Review by buraizu — APPROVED** [review]

**Comment by brett0000FF** [comment]
@vidurkhannadatadog - I worked with @zacharycmontoya to improve these examples. Let me know if you have any more feedback. Thanks!

**Comment by zacharycmontoya** [comment]
> @vidurkhannadatadog - I worked with @zacharycmontoya to improve these examples. Let me know if you have any more feedback. Thanks!

In the description we built off the Java text and added some small examples. If you think this is good, we might also want to apply it to other language pages as well, with their respective config names

**Comment by brett0000FF** [comment]
Creating a separate Jira card for the other langauges, so I can get this PR merged more quickly.
https://datadoghq.atlassian.net/browse/DOCS-6346

**Pull request merged**
