### PR TITLE
docs: add new node.js custom metrics api

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?
- adds documentation for upcoming Node.js custom metrics API

### Motivation
- users gotta know how to use it

### Additional Notes
- don't merge until https://github.com/DataDog/dd-trace-js/pull/3518 merges

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by brett0000FF — APPROVED** [review]
LGTM! Let me know if you need me to merge this.

**Comment by avedmala** [comment]
I found [this page](https://docs.datadoghq.com/integrations/node/) also has instructions on how to use `hot-shots`

Could we point the Metric collection section of that page to the example you added or does the private repo mentioned in [dd-trace-js/pull/3518](https://github.com/DataDog/dd-trace-js/pull/3518) handle that?

**Comment by tlhunter** [comment]
@avedmala there is a separate PR for that page. I'd link to it here but it's an internal repo.

**Comment by tlhunter** [comment]
@avedmala yes, the other PR does update that page to link to the page updated in this PR.

**Pull request merged**
