### PR TITLE
Mattw/jenkins59

### PR DESCRIPTION
**Pull request by technovangelist**

### CODE REVIEW

**Comment by irabinovitch** [comment]
@technovangelist  we probably still want to have docs here about the jenkins plugin, but im not sure if that goes in another page.  

Having a deprecation note about the agent-check makes sense. We should add one in the YAML config in dd-agent, and in the tile as well.

**Comment by technovangelist** [comment]
keeping docs on the plugin that is maintained in a different repo increases chances that it's going to get out of sync. I guess the same could be said about other integrations, but this seems even more likely here.

**Comment by irabinovitch** [comment]
We develop the plugin, so having things like metrics metrics metadata and other similar niceties of our docs site keeps it on par with our other integrations.

**Comment by technovangelist** [comment]
cool, will update

**Comment by technovangelist** [comment]
ok, integration updated

**Pull request closed without merging**
