### PR TITLE
Add search terms for ksm

### PR DESCRIPTION
**Pull request by hestonhoffman**
Need to test before merging

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.
- [ ] Check that `cache_enabled` is set to `true` in the `pull_config_preview.yaml` file

### CODE REVIEW

**Comment by nsollecito** [comment]
should we look at defining a synonym for "ksm" as well?

**Comment by hestonhoffman** [comment]
@nsollecito Yes, I think that's a good idea. I'll add it to the algolia file. I just realized I haven't been doing this to other abbreviations 😨 I'll do a search for those later

**Comment by hestonhoffman** [comment]
@nsollecito Does the object ID need to be one word?

**Comment by nsollecito** [comment]
> @nsollecito Does the object ID need to be one word?

yes, I think it should be.. according to the docs, the object id is a unique identifier for the entry: https://www.algolia.com/doc/api-reference/api-methods/save-synonym/#createupdate-a-regular-synonym-where-all-the-words-are-equivalent

The array containing the synonyms in this config treats all of the values as if they were equal, so it's not a mapping between the object id and the synonym values. If you want to include a one-way mapping, it looks like we need to use a different structure. Let me know if you want us to take a closer look. 

cc @bgdeutsch

**Comment by hestonhoffman** [comment]
> > @nsollecito Does the object ID need to be one word?
> 
> yes, I think it should be.. according to the docs, the object id is a unique identifier for the entry: https://www.algolia.com/doc/api-reference/api-methods/save-synonym/#createupdate-a-regular-synonym-where-all-the-words-are-equivalent
> 
> The array containing the synonyms in this config treats all of the values as if they were equal, so it's not a mapping between the object id and the synonym values. If you want to include a one-way mapping, it looks like we need to use a different structure. Let me know if you want us to take a closer look.
> 
> cc @bgdeutsch

Gotcha - Not sure a one-way mapping is really necessary in this case, so I folded all of the terms into the single entry. A closer look would be great :)

**Review by nsollecito — APPROVED** [review]

**Review by rtrieu — APPROVED** [review]
Looks great, thank you so much!

**Pull request merged**
