### PR TITLE
Video & Example dir added to JP directory,  also auto ”sidebar &  top menu” generation added.

### PR DESCRIPTION
**Pull request by jhotta**

### CODE REVIEW

**Comment by technovangelist** [comment]
Hi Jay,   

Still looking into this and will sync up

**Comment by jhotta** [comment]
I have merged my pull request to under the ja-jp branch,  so you can checkout and compile test it.

**Comment by alq666** [comment]
@technovangelist this is blocking @jhotta. Can you review? Or should he merge directly?

**Comment by technovangelist** [comment]
I had discussed this with j. it was breaking the docs last I looked.

**Comment by technovangelist** [comment]
I hadn't seen that this was resolved...

**Pull request merged**
