### PR TITLE
Unifies shortcode delimiters

### PR DESCRIPTION
**Pull request by bgdeutsch**
### What does this PR do?
- Replaces most instances of {{% shortcode %}} with {{< shortcode >}}
- Updates tabs.html shortcode to have the markdownify hugo pipe

### Motivation
#15236 

Long running issues with mixing the `%%` and `<>` shortcodes when nested.

### Preview
all content within tabs should be rendered correctly (with no visible plaintext markdown), there should be no visual issues around the site, no content removed and no build problems.

general site QA (particularly around tabs): https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update

some pages to check:
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update/integrations/slack/?tab=slackapplication
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update/database_monitoring/setup_sql_server/azure/ (check before you begin section renders correctly as well as tabs content is not removed)
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update/integrations/guide/aws-manual-setup/?tab=roledelegation#aws-iam-permissions
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update/account_management/rbac/permissions
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update/account_management/billing/custom_metrics/
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update/tracing/trace_collection/dd_libraries/ruby/
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes-update/real_user_monitoring/error_tracking/android/?tab=us
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/api/latest
- https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/integrations

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by davidejones** [comment]
@bgdeutsch I know we had some sections with `{{< tab "MySQL ≥ 8.0" >}}` or with `>` or `<` in the tab name string. Do these pass the scripted format changes? I see in the PR it didn't change them

**Review by davidejones — APPROVED** [review]
Tested as many pages as i could and reviewed various file changes. It seems good, just need to resolve the conflict.

**Review by djmitche — APPROVED** [review]
`content/en/agent/proxy.md` 👍🏽

**Review by hestonhoffman — APPROVED** [review]

**Comment by hestonhoffman** [comment]
Docs team took a look and this is looking good 👍

**Pull request merged**
