### PR TITLE
parse preprocessed rules

### PR DESCRIPTION
**Pull request by davidejones**
### What does this PR do?

Some of the security rules are now preprocessed. This PR attempts to process them so we can get some yaml out to generate docs rules.

### Motivation

To include rules that are being skipped

### Preview

see this url vs prod
https://docs-staging.datadoghq.com/david.jones/template-parse/security_platform/default_rules/#cat-workload-security

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by bgdeutsch — APPROVED** [review]

**Comment by n06** [comment]
Thanks @davidejones! This looks good with two small nites:

- Can we change the section header of "Runtime Security" to "Cloud Workload Security"
- We seem to be missing tags for CWS rules. We can follow up on this in a subsequent PR though

**Comment by davidejones** [comment]
@n06 

- This can be changed by updating the source attribute in the yaml files from `source: Runtime Security` to `source: Cloud Workload Security` and it should group them accordingly on docs
- Can you make a card on our board for this one and we can take a look

**Comment by n06** [comment]
> @n06
> 
> * This can be changed by updating the source attribute in the yaml files from `source: Runtime Security` to `source: Cloud Workload Security` and it should group them accordingly on docs
> * Can you make a card on our board for this one and we can take a look

Will do!

**Review by alai97 — APPROVED** [review]
Looks good for docs!

**Pull request merged**
