### PR TITLE
Document Sankey visualization and create Product Analytics section of nav

### PR DESCRIPTION
**Pull request by jhgilbert**
### What does this PR do? What is the motivation?
DOCS-7729

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by rtrieu — APPROVED** [review]
Minor suggestion to follow our guidelines, but otherwise looks great!

**Comment by jamiemilstein** [comment]
just following up on the last comment, can we add a banner up top to state this is in public beta?

and we are good to merge this on thursday 3/7

**Comment by jamiemilstein** [comment]
these are all good to be merged ,thanks!!

**Comment by jamiemilstein** [comment]
@jhgilbert and @rtrieu just wanted to follow up on this again: can we push this live today?

**Pull request merged**
