### PR TITLE
adding a new integration to community libraries

### PR DESCRIPTION
**Pull request by apigirl**
### What does this PR do?
Adds APISIX to the community library page

https://docs-staging.datadoghq.com/kaylyn/community-new/developers/community/libraries/

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by jeremy-lq — APPROVED** [review]

**Comment by yzeng25** [comment]
Hi @apigirl @jeremy-lq ,

Thanks for doing this! There is one small issue needs to be updated in the "Language" section in the chart.

image

The "Language" of the APISIX-Datadog Plugin is actually written in Lua instead of "Apache".

**Comment by yzeng25** [comment]
Hi @apigirl @jeremy-lq ,

Pull requests https://github.com/DataDog/the-monitor/pull/139 and https://github.com/DataDog/documentation/pull/12234, and issue https://github.com/DataDog/the-monitor/issues/138 are closed now. 
Please kindly fix the Language column and merge it when you have time. Thanks!

**Comment by apigirl** [comment]
@yzeng25 - thanks for the feedback! I have updated and we're merging soon.

**Review by kayayarai — APPROVED** [review]

**Comment by yzeng25** [comment]
> @yzeng25 - thanks for the feedback! I have updated and we're merging soon.

Cool. Thanks for your update!

**Pull request merged**
