### PR TITLE
Add section about Playback History

### PR DESCRIPTION
**Pull request by acorretti**
### What does this PR do? What is the motivation?

Session Replay is adding a Playback History feature.

### Merge instructions

- [x] Please **wait for @jamiemilstein approval** before merging. Needs coordination with the feature announcement e-mail.

### CODE REVIEW

**Comment by jamiemilstein** [comment]
@jhgilbert do you mind adding an editorial review to this one? TY!

**Comment by jamiemilstein** [comment]
re: merging this, all good to merge when this is live in all orgs. @acorretti have we done the rollout yet? FA won't go out until it's enabled in all orgs

**Comment by jhgilbert** [comment]
@acorretti or @jamiemilstein , are you able to provide a higher-resolution screenshot? I tried to take one myself, but the feature doesn't seem to be live in Demo. Let me know if there's a feature flag I can use to take the screenshot in Demo, happy to update the image.

**Comment by acorretti** [comment]
> @acorretti or @jamiemilstein , are you able to provide a higher-resolution screenshot? I tried to take one myself, but the feature doesn't seem to be live in Demo. Let me know if there's a feature flag I can use to take the screenshot in Demo, happy to update the image.

The problem is that the names & dates displayed must be made-up, so I edited them out of the figma designs.
What's the resolution you'd need? I thought focusing the capture on just the pop-over content would suffice.

**Comment by jhgilbert** [comment]
> > @acorretti or @jamiemilstein , are you able to provide a higher-resolution screenshot? I tried to take one myself, but the feature doesn't seem to be live in Demo. Let me know if there's a feature flag I can use to take the screenshot in Demo, happy to update the image.
> 
> @jhgilbert The problem is that the names & dates displayed must be made-up, so I edited them out of the figma designs. What's the resolution you'd need? I thought focusing the capture on just the pop-over content would suffice.

@acorretti The docs team shares the same issue with needing to anonymize users, but we have some tooling that allows us to do that in the Datadog UI. I'll just add my own screenshot to this today, that's probably the quickest solution. Thank you!

**Review by jhgilbert — APPROVED** [review]

**Comment by acorretti** [comment]
We're releasing along this week. Will ping you back here when we're 100% in all DCs @jamiemilstein @jhgilbert

**Pull request merged**
