### PR TITLE
Update and correct host mute API docs

### PR DESCRIPTION
**Pull request by wang-arthur**
- Correct endpoint URL
- Revise host muting docs for clarity and accuracy
- Add ruby and shell code snippets

- Requires https://github.com/DataDog/dogapi-rb/pull/67

### CODE REVIEW

**Comment by jhotta** [comment]
@technovangelist can you please look at the `api-host-mute.rb` file under code_snippets directory.  Even though, rake compile display an error message, I can not find any error in the ruby script.

**Comment by technovangelist** [comment]
What changes did you make to the code?

On Thu, May 28, 2015 at 3:29 AM, Jay Hotta <notifications@github.com> wrote:

> @technovangelist <https://github.com/technovangelist> can you please look
> at the api-host-mute.rb file under code_snippets directory. Even though,
> rake compile display an error message, I can not find any error in the ruby
> script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DataDog/documentation/pull/408#issuecomment-106209359>
> .
>



-- 
Matt Williams
DevOps Evangelist - Datadog
mattw@datadoghq.com
@technovangelist

**Comment by jhotta** [comment]
I have not changed anything.  I was testing arthur's code before merging.
In the branch `update_host_muting`, I got the following error log trace.

---
% rake compile
bundle exec nanoc compile
Loading site data… done
Compiling site…
/var/folders/8l/m3th7yrx33vc_pgp0fr47qy00000gn/T/foo20150601-37010-znytzc:13:in `wrapper': undefined method `mute_host' for #<Dogapi::Client:0x007f9a05900140> (NoMethodError)
	from /var/folders/8l/m3th7yrx33vc_pgp0fr47qy00000gn/T/foo20150601-37010-znytzc:17:in `<main>'

Captain! We’ve been hit!

Message:

RuntimeError: error executing api-host-mute.rb

Compilation stack:

  - [item]   /api/ (rep default)

Stack trace:

  0. lib/snippets.rb:119:in `eval_snippet'
  1. lib/snippets.rb:36:in `snippet_result_code_block'
  2. item /api/ (rep default):1221:in `get_binding'
  3. /Users/papago/.rbenv/versions/2.1.5/lib/ruby/2.1.0/erb.rb:850:in `eval'
  4. /Users/papago/.rbenv/versions/2.1.5/lib/ruby/2.1.0/erb.rb:850:in `result'
  5. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/filters/erb.rb:33:in `run'
  6. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/filter.rb:117:in `setup_and_run'
  7. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/result_data/item_rep.rb:334:in `filter'
  8. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/item_rep_proxy.rb:45:in `filter'
  9. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/rule_context.rb:59:in `filter'
  ... 28 more lines omitted. See full crash log for details.

If you believe this is a bug in nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.
rake aborted!
Command failed with status (1): [bundle exec nanoc compile...]
/Users/papago/GitRepos/org-dd-docs/Rakefile:16:in `block in <top (required)>'
Tasks: TOP => compile
(See full trace by running task with --trace)
/Users/papago/GitRepos/org-dd-docs%

**Comment by jhotta** [comment]
@wang-arthur Can you release update of the dogapi ruby gem (it's outedated).  The current gem version of 1.17.0 dose not have the *host_mute* function and will only give is " undefined method `mute_host' for #<Dogapi::Client:0x007fd6148e5458> (NoMethodError)"

**Comment by jhotta** [comment]
@wang-arthur You also need to fix Gemfile and Gemfile.lock with the updated version # of dogapi-rb.  If you will release the update of dogapi-rb gem, I'm willing to work on these changes.

**Comment by wang-arthur** [comment]
Sure thing, @jhotta. Thanks! I'll let you know when the new gem has been released.

**Comment by yannmh** [comment]
New gem has been released.

**Comment by jhotta** [comment]
thanks @yannmh! It did fixed ruby part.  
Now I'm working on the following:

rake compile
bundle exec nanoc compile
Loading site data… done
Compiling site…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1166  100  1166    0     0    838      0  0:00:01  0:00:01 --:--:--   838
No JSON object could be decoded

Captain! We’ve been hit!

Message:

RuntimeError: error executing api-host-unmute.sh

Compilation stack:

  - [item]   /api/ (rep default)

Stack trace:

  0. lib/snippets.rb:119:in `eval_snippet'
  1. lib/snippets.rb:36:in `snippet_result_code_block'
  2. item /api/ (rep default):1243:in `get_binding'
  3. /Users/papago/.rbenv/versions/2.1.5/lib/ruby/2.1.0/erb.rb:850:in `eval'
  4. /Users/papago/.rbenv/versions/2.1.5/lib/ruby/2.1.0/erb.rb:850:in `result'
  5. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/filters/erb.rb:33:in `run'
  6. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/filter.rb:117:in `setup_and_run'
  7. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/result_data/item_rep.rb:334:in `filter'
  8. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/item_rep_proxy.rb:45:in `filter'
  9. /Users/papago/GitRepos/org-dd-docs/vendor/bundle/ruby/2.1.0/gems/nanoc-3.7.5/lib/nanoc/base/compilation/rule_context.rb:59:in `filter'
  ... 28 more lines omitted. See full crash log for details.

If you believe this is a bug in nanoc, please do report it at
-> https://github.com/nanoc/nanoc/issues/new <-

A detailed crash log has been written to ./crash.log.
rake aborted!
Command failed with status (1): [bundle exec nanoc compile...]
/Users/papago/GitRepos/org-dd-docs/Rakefile:16:in `block in <top (required)>'
Tasks: TOP => compile
(See full trace by running task with --trace)

**Comment by wang-arthur** [comment]
Thanks @yannmh! @jhotta, I'll take a look at this error.

**Comment by technovangelist** [comment]
Don't worry too much about that. If the code sample works and that's the only
issue then merge.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2]
On Mon, Jun 1, 2015 at 11:34 AM, Arthur <notifications@github.com> wrote:
Thanks @yannmh [https://github.com/yannmh] ! @jhotta [https://github.com/jhotta] , I'll take a look at this error.

—
Reply to this email directly or view it on GitHub
[https://github.com/DataDog/documentation/pull/408#issuecomment-107587677] .[https://github.com/notifications/beacon/AAmrUVKfrcYTeU0SfY41yJLPkr0MppNgks5oPHL8gaJpZM4ElW3O.gif]

**Comment by jhotta** [comment]
merged arthur's fix and update gem requirements

**Pull request merged**
