### PR TITLE
Mark roadrunner 3.x as supported

### PR DESCRIPTION
**Pull request by bwoebi**
First, roadrunner 3.x is supported.

However, some users have been confused because the SDK (https://github.com/roadrunner-php/http) is versioned differently from the web server (https://github.com/roadrunner-server/roadrunner).
These are independent, but people have been asking for whether we support version "2024.2", while the real thing they would need to know is if we support Roadrunner SDK 3.x (but they don't really grasp that).

Is there anything we can do here to make this clearer to viewers of that documentation page?

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Comment by buraizu** [comment]
Thanks, created DOCS-9258 to investigate if there's anything else we can do here to make this clearer to viewers of this documentation page

**Review by brett0000FF — APPROVED** [review]
@bwoebi - Apologies for the delay on this! I think this is a good opportunity to use our new tooltip feature so we don't clutter the table, but we can include info about the version discrepancy.

What do you think of the change I pushed?

**Comment by brett0000FF** [comment]
@PROFeNoM - What do you think of this change I pushed to clarify the customer confusion Bob highlighted? He's OOO so requested that I ping you. Thanks!

**Review by PROFeNoM — APPROVED** [review]
For me, this looks good! (+it's beautiful 😃)

**Pull request merged**
