### PR TITLE
[CLOUDCRAFT-718] Update Cloudcraft's "Create your first live AWS diagram" article

### PR DESCRIPTION
**Pull request by jamesponddotco**
### What does this PR do? What is the motivation?
Updates this article to better match the current version of Cloudcraft and better follow the style guide. I still feel like it misses a conclusion, though. Suggestions are welcome :)

### Merge instructions
- [x] Please merge after reviewing

### CODE REVIEW

**Comment by brett0000FF** [comment]
Thanks! Created DOCS-8238 to review these changes.

**Review by aliciascott — CHANGES_REQUESTED** [review]
Hi @jamesponddotco ! I have quite a few suggestions to align with our style guide a bit better where needed and general overall flow to help guide the users through the setup. Also I re-worded the conclusion a bit more to help with the flow there, let me know if you had any questions! 
Please request another review once you've updated the suggestions, thanks!

**Comment by jamesponddotco** [comment]
@aliciascott Sorry, I was out for a portion of last week. The suggestions have been applied :)

**Comment by aliciascott** [comment]
> @aliciascott Sorry, I was out for a portion of last week. The suggestions have been applied :)

Thanks @jamesponddotco it looks like there is now a merge conflict with a file, can you fix that and then I'll review and get it merged? Thanks!

**Review by aliciascott — APPROVED** [review]

**Pull request merged**
