### PR TITLE
[SCICM-2890][Source Code Integration] Fix minimal CLI versions

### PR DESCRIPTION
**Pull request by rpelliard**
### What does this PR do? What is the motivation?

This PR:
- Fixes the minimum datadog-ci version that is required for Source Code Integration
- Updates the command output sample with the latest version
- Adds the minimal version requirement directly where people are prompted to install datadog-ci.
- 
Preview: https://docs-staging.datadoghq.com/ronan/sci-fix-cli-versions/integrations/guide/source-code-integration/?tab=othergitproviders

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Comment by jhgilbert** [comment]
Hi @rpelliard, I see that this has conflicts. Let me know if you need any help resolving those. Thanks!

**Comment by rpelliard** [comment]
> Hi @rpelliard, I see that this has conflicts. Let me know if you need any help resolving those. Thanks!

@jhgilbert thanks for flagging ! This should be fixed now

**Review by rtrieu — APPROVED** [review]
LGTM

**Review by jminuscula — APPROVED** [review]

**Comment by rpelliard** [comment]
@rtrieu we're good to merge, thanks !

**Pull request merged**
