### PR TITLE
Add eppo feature flag integration

### PR DESCRIPTION
**Pull request by leoromanovsky**
### What does this PR do? What is the motivation?

Adds instructions for integrating Datadog's feature flagging product with Eppo's SDKs on the iOS, Android and Javascript browser platforms.

Follows formatting and style conventions on the existing page.

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Comment by drichards-87** [comment]
Created DOCS-7614 for Docs Team editorial review.

**Review by Miz85 — COMMENTED** [review]
Thank you for documenting this integration! I have a few comments/suggestions.

**Comment by rtrieu** [comment]
Hi @leoromanovsky , when you have incorporated @Miz85's feedback, please feel free to comment and tag me, or request a review from me, and I will be happy to publish it to our docs. Thank you!

**Comment by emetelka** [comment]
@rtrieu I've updated based on the suggested changes

**Review by rtrieu — APPROVED** [review]
Looks good!

**Comment by rtrieu** [comment]
Hi @emetelka, thank you for making those changes! Just FYI, I've copied everything over to this PR so that we could generate a preview of the new content: [https://github.com/DataDog/documentation/pull/22747](https://github.com/DataDog/documentation/pull/22747)

**Comment by rtrieu** [comment]
Closing this PR after forking: https://github.com/DataDog/documentation/pull/22747

**Pull request closed without merging**
