### PR TITLE
Frontend impact feature description

### PR DESCRIPTION
**Pull request by lee-brian**
### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Review by adriane-cardoso — COMMENTED** [review]
LGTM!

**Comment by hestonhoffman** [comment]
👋 Hi, can you remove the changes to the `go.sum` and `go.mod` from the PR?

**Review by lee-brian — COMMENTED** [review]
Updated to incorporate feedback

**Review by hestonhoffman — APPROVED** [review]

**Pull request merged**
