### PR TITLE
update header footer to use menu config files

### PR DESCRIPTION
**Pull request by zbayoff**
### What does this PR do?
1. Updates Docs footer to use new corpsite design (already live on corp). 
2. Moves menu config to the `config/` folder rather than `data/` as was the old way of doing things. 

### Motivation
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?assignee=5d4b49d50fa6d40d14fc7b11&selectedIssue=WEB-793

### Preview
Review header and footer links and functionality, at diff breakpoints.

http://docs-staging.datadoghq.com/zach/new-footer
http://docs-staging.datadoghq.com/zach/new-footer/ja
http://docs-staging.datadoghq.com/zach/new-footer/fr

### CODE REVIEW

**Comment by nsollecito** [comment]
Relative footer links for JA and ES are going to a 404

**Comment by nsollecito** [comment]
Actually, all corpsite links in footer are going to 404

**Comment by zbayoff** [comment]
@nsollecito Updated footer links.

**Comment by davidejones** [comment]
I notice some issues with the header on the english site
image

and in french
image

**Comment by davidejones** [comment]
Also the current ja/fr footer on docs is translated. Is there anyway we can retain the translations for links whose text hasn't changed?

**Comment by zbayoff** [comment]
> I notice some issues with the header on the english site
> image
> 
> and in french
> image

The french CTA is a little off on Docs live as well. I've made adjustments, but i think its probably better on the right side anyways for now, until design gives us a better solution.

**Review by davidejones — APPROVED** [review]
looks good here

**Review by kayayarai — APPROVED** [review]

**Pull request merged**
