### PR TITLE
Updated Native Database setups steps to include reference to the inte…

### PR DESCRIPTION
**Pull request by avaughan89**
…gration tile steps

### CODE REVIEW

**Comment by irabinovitch** [comment]
@avaughan89  since most of these have docs here in documentation maybe just link them directly from here?

**Comment by avaughan89** [comment]
@irabinovitch Updated to include links to the 3 docs.

**Comment by technovangelist** [comment]
Im not sure i see the value of this addition. What is the flow supposed to be? It looks like you are saying, before you update the yaml file as it is shown here, go to this other page, update the yaml, then come back here and update the yaml again. So what is the value of going to the configuration on the other page??

**Comment by avaughan89** [comment]
@technovangelist A customer referenced that the doc did not make it clear you needed to complete the database steps before editing the yaml file.  This change is not *necessary* but it addresses their concerns and clears up the confusion.  My original commit followed that a little closer.

**Comment by technovangelist** [comment]
if the change is not needed, why have them do it

**Comment by irabinovitch** [comment]
Theres definitely room for improving this doc.  I'm not sure if repeating the docs for each of the native integrations here makes sense. I like Andrew's approach of mentioning that native metrics are available, and linking to the appropriate pages.

**Comment by technovangelist** [comment]
the problem was that it was a change to the docs that wasn't tested and wasn't known to make any difference. and then it was telling people to follow some instructions on a different page, but not directing them to 'which' of the page of instructions, since there were some that you should not do, even if it did make a difference....

I think this should be collapsed a bit. people choose which of the 3 integrations they want and do it. making people click around to other pages gets confusing. When i do that I can't remember where i was.

**Pull request closed without merging**
