### PR TITLE
apm/python: update links

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
### What does this PR do?

Updates the links in the docs for when https://github.com/DataDog/dd-trace-py/pull/1635 is merged and deployed.

### CODE REVIEW

**Comment by Kyle-Verhoog** [comment]
@DataDog/documentation could someone please review this? We'll be updating our docs with our next release and these links need to be updated 🙂

**Review by kayayarai — APPROVED** [review]
Looks good. Let me know when the links go live and we can merge.

**Comment by Kyle-Verhoog** [comment]
thanks @kayayarai!

**Comment by Kyle-Verhoog** [comment]
Heh I made a bit of a mess by merging locally (and having the precommit hooks run over all the merged files). Cleaned up now 😆. 

@kayayarai we'll be releasing later today. I'll let you know when so we can merge 🙂

**Comment by Kyle-Verhoog** [comment]
@kayayarai we just released so this can be merged now, thanks! 😄

**Comment by kayayarai** [comment]
@Kyle-Verhoog So you're aware, the translation build will overwrite these changes in the ja and fr (some happened last night), but they'll get re-applied when the translation of these pages catches up to the English source. Our fr and ja content origin is transifex, not github

**Comment by Kyle-Verhoog** [comment]
Oh I see. Hmm I'll see if we can provide redirects for the links in the mean-time.

**Pull request merged**
