### PR TITLE
WEB-2391 - integration tile styles

### PR DESCRIPTION
**Pull request by davidejones**
### What does this PR do?

Update integrations tiles styling

### Motivation

https://datadoghq.atlassian.net/browse/WEB-2391

### Preview

https://docs-staging.datadoghq.com/david.jones/integration-style/integrations/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by davidejones** [comment]
Ready for reviews but do not merge yet

**Review by bgdeutsch — COMMENTED** [review]
i noticed a few tiles using what look to be the old (smaller) integration logos.  for example `TCP Check` and `Kubernetes State Metrics Core`.   also noticed a display overlap issue for one of the other tiles https://a.cl.ly/Kouj8Bxk

**Comment by davidejones** [comment]
@bgdeutsch Will you take another look at this when you get a moment

**Review by bgdeutsch — APPROVED** [review]
LGTM 💯

**Review by cswatt — APPROVED** [review]

**Pull request merged**
