### PR TITLE
Update DBM K8s config documentation

### PR DESCRIPTION
**Pull request by aweaver89**
Fix issue with double quote (") not being closed correctly and the extra escaping of the . before `.yaml` since this is the name of a file.

### Additional Notes

---

### Reviewer checklist
- [x] Review the changed files.
- [x] Review the URLs listed in the [Preview](#preview) section.
- [x] Check images for PII
- [x] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by aweaver89** [comment]
@cswatt - should be good now :)

**Review by drichards-87 — APPROVED** [review]
PR is approved. Let me know if you'd like anyone else to look at it before it gets merged.

**Comment by drichards-87** [comment]
@aweaver89 Just wanted to follow-up on this. Is this ready to be merged?

**Comment by aweaver89** [comment]
hey @drichards-87 - yup this is good but it looks like there are still others that need to approve? It doesn't look like I'm able to merge on my end yet...

**Comment by drichards-87** [comment]
@aweaver89 I would post a link to this PR in the DBM Slack channel requesting a review. Only Docs Team members can merge in this repo, so I'll need to do that for you after the DBM team approves the PR.

**Review by jmeunier28 — APPROVED** [review]
lgtm

**Comment by aweaver89** [comment]
All good for merging now @drichards-87 ?
Let me know if I need to do anything else :)

**Comment by drichards-87** [comment]
Thanks @aweaver89. I'll get this merged now.

**Pull request merged**
