### PR TITLE
Azure integration doc

### PR DESCRIPTION
**Pull request by 2bethere**
This the V1 doc. Doesn't include extension deployment instructions as that's still under development.

### CODE REVIEW

**Comment by technovangelist** [comment]
Hey Will, before merging this in can you make one change? I see you manually added the list of integrations. This means that the list appears twice. Can you remove your manual list?

**Comment by 2bethere** [comment]
Reverted to Matt's version of auto list generation.

**Comment by technovangelist** [comment]
Before doing a pull request, can you do a rake clean, then rake. That will catch any errors in the build. It currently will not build due to the changes in the index file.

**Comment by 2bethere** [comment]
My bad, should have built again after reverting. Now there is no error.

**Comment by technovangelist** [comment]
i merged it and then added another pr to add kind: integration and integration title: Microsoft Azure so that the doc is auto added to the generated list of integrations

**Pull request merged**
