### PR TITLE
Basic metrics-collection info for etcd

### PR DESCRIPTION
**Pull request by johnaxel**

### CODE REVIEW

**Comment by johnaxel** [comment]
Since we're going to announce our etcd integration soon, @kky and I thought it would be good to have some basic docs to point to. Does this look OK to you @technovangelist @degemer?

**Comment by degemer** [comment]
@johnaxel looks good to me.
I don't know if it's relevant, but you could add that etcd metrics are tagged with `etcd_state:leader` or `etcd_state:follower`, depending on the node status.

**Comment by alq666** [comment]
Excellent point. Tags do matter.

**Comment by johnaxel** [comment]
Thanks, Quentin! Just pushed a small change to add the tagging info.

**Pull request merged**
