### PR TITLE
quote shell variable values (and remove trailing whitespace)

### PR DESCRIPTION
**Pull request by dgoffredo**
### What does this PR do?
Some example configurations in the new "ingestion sampling use cases" guide are expressed as what looks like command shell variable assignments, e.g.

    SOME_VARIABLE=some text containing spaces

Command shells don't understand grouping characters (e.g. `[` or `{`) in the context of variable assignments, and so the above example in general assigns the value "`some`" and then attempts to run the command `text containing spaces`.

This pull request places the entire `some text containing spaces` into single quotes, so that a customer could copy/paste the line into a shell and it will have the intended effect (though it will not `export` the variable to the environment of child processes...).

My code editor also automatically removed trailing whitespace from some unrelated lines, I think.

### Motivation
I was reading through the new guide and noticed this.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by dussault-antoine — APPROVED** [review]

**Review by buraizu — APPROVED** [review]
LGTM (pending preview)

**Comment by dgoffredo** [comment]
ping @buraizu

**Comment by buraizu** [comment]
Confirmed via Slack that code freeze is not in effect. Apologies for the delay, and please feel free to reach out via Slack for merging.

**Comment by dgoffredo** [comment]
thanks!

**Pull request merged**
