### PR TITLE
Update datadog-aas-linux version in azure_app_services_linux.md

### PR DESCRIPTION
**Pull request by apiarian-datadog**
### What does this PR do? What is the motivation?

Update the version of the DataDog/datadog-aas-linux datadog_wrapper to the latest.

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by drichards-87 — APPROVED** [review]
@apiarian-datadog Looks good! Is this ready to be merged now?

Also, just FYI, if you include a forward slash in your branch name (.e.g., `apiarian/datadog-patch-1`), it'll generate a staging preview of the docs site with your changes. For small changes such as this, we can review in GitHub. But for larger updates, we'll typically want to view the updates in staging.

**Comment by apiarian-datadog** [comment]
> > @apiarian-datadog Looks good! Is this ready to be merged now?
> > Also, just FYI, if you include a forward slash in your branch name (.e.g., `apiarian/datadog-patch-1`), it'll generate a staging preview of the docs site with your changes. For small changes such as this, we can review in GitHub. But for larger updates, we'll typically want to view the updates in staging.
> 
> yup, i think this is ready to be merged, though some test failed and i'm going to rebase it. i'll make sure to include the slash next time, i was using the github ui to make the tiny change =]

@drichards-87 is the branch name issue the reason that the preview synthetics check is failing?

**Comment by drichards-87** [comment]
> > > @apiarian-datadog Looks good! Is this ready to be merged now?
> > > Also, just FYI, if you include a forward slash in your branch name (.e.g., `apiarian/datadog-patch-1`), it'll generate a staging preview of the docs site with your changes. For small changes such as this, we can review in GitHub. But for larger updates, we'll typically want to view the updates in staging.
> > 
> > 
> > yup, i think this is ready to be merged, though some test failed and i'm going to rebase it. i'll make sure to include the slash next time, i was using the github ui to make the tiny change =]
> 
> @drichards-87 is the branch name issue the reason that the preview synthetics check is failing?

Yes, that could be one reason why. It isn't unusual for the synthetics checks to occasionally fail; they're not a block to merging the PR though. The main checks that are blocking are the build preview and link checker jobs.

**Comment by apiarian-datadog** [comment]
replaced with https://github.com/DataDog/documentation/pull/24930 to fix the branch name issue

**Pull request closed without merging**
