### PR TITLE
update tab usage

### PR DESCRIPTION
**Pull request by davidejones**
### What does this PR do?

Reimplements #16811  (revert at #16817) in addition to fixing dropdowns

### Motivation

Fixing issues after release / synthetic

### Preview

Check language dropdown and site dropdown on the right works
https://docs-staging.datadoghq.com/david.jones/fixes/infrastructure

Check the v1/v2 tabs here and the link in the alert/callout
Check language & site dropdowns work
https://docs-staging.datadoghq.com/david.jones/fixes/api/latest/events

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by urseberry** [comment]
I am seeing some strange behavior.

1. Navigate to an API page
2. Navigate to a non-API page
3. Change language to French
4. The page refreshes to show the page from step 1 in French. Expected behavior is to show the page on step 2.

**Review by fitzage — APPROVED** [review]

**Comment by urseberry** [comment]
1. Navigate to https://docs-staging.datadoghq.com/david.jones/fixes/logs/guide/
2. Change site to EU
3. Change language to French
4. In the left nav, click on CI Visibility->Tests de tracing
Expected behavior: Page updates to show the Tests de tracing page
Actual behavior: Page stays on the Logs guide page

**Comment by urseberry** [comment]
> 1. Navigate to https://docs-staging.datadoghq.com/david.jones/fixes/logs/guide/
> 2. Change site to EU
> 3. Change language to French
> 4. In the left nav, click on CI Visibility->Tests de tracing
>    Expected behavior: Page updates to show the Tests de tracing page
>    Actual behavior: Page stays on the Logs guide page

Hmm, maybe this is a bit strange in the live docs as well? I tried out this sequence of steps in the main docs, but as I executed step 3, the page refreshed to show CI Visibility.

**Comment by urseberry** [comment]
I can definitely get into a state where the left nav doesn't work.

1. Navigate to https://docs-staging.datadoghq.com/david.jones/fixes/logs/guide/
2. Change site to EU
3. Change language to French
4. Start clicking around in the left nav.
Sorry, I stopped tracking exactly what I was clicking on. But after a while, clicking an item in the left nav fails to change the page.

**Review by urseberry — APPROVED** [review]
The left nav issue is reproducible in prod also. I'll open a separate ticket to track.

The docs team didn't find any other issues with this PR. Approved. Ping us in #documentation when you want this merged.

**Comment by urseberry** [comment]
Created a ticket for the unrelated bug: https://datadoghq.atlassian.net/browse/WEB-3172

**Comment by davidejones** [comment]
Thanks @urseberry this can merge anytime, if you guys are ready

**Pull request merged**
