### PR TITLE
Redirect pricing to help billing page

### PR DESCRIPTION
**Pull request by technovangelist**

### CODE REVIEW

**Comment by irabinovitch** [comment]
merging but lets do a true 301 in S3

**Comment by irabinovitch** [comment]
@marcweisman this is a temporary hack

**Comment by technovangelist** [comment]
its basically updating the page to show
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>#{redirect[:from]}</title>
    <meta http-equiv="refresh" content="0;URL='#{redirect[:to]}'" />
  </head>
  <body>
    <p>This page has moved to <a href="#{redirect[:to]}">#{redirect[:to]}</a>.</p>
  </body>
</html>`

and redirecting to the page on the help site. should redirect with no delay, but I kept seeing a delay

**Comment by marcweisman** [comment]
Thanks!

**Pull request merged**
