### PR TITLE
Suggest the Jetbrains Marketplace for IntelliJ

### PR DESCRIPTION
**Pull request by bric3**
Note this PR is the sibling of https://github.com/DataDog/documentation/pull/15628 with discussed suggestions and fixes. Renaming the branch as suggested in this [comment](https://github.com/DataDog/documentation/pull/15628#issuecomment-1285887998) did close the PR.

Cc @buraizu 

### What does this PR do?

@vidurkhannadatadog Received some feedback at DASH on the documentation, where a backlink to the market place was missing. Ultimately the proposed change was to use the related UI elements of the JetBrains Market place by introducing this piece of code.

image

As I wasn't sure if this was OK to

1. use UI material from Jetbrains there,
2. use an external script in this website

So I went with a simple URI. Feel free to iterate on this.

### Motivation

CC @@vidurkhannadatadog

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by buraizu** [comment]
@bric3 thank you for renaming your branch and generating the preview. Could you clarify how you're confirming that, so I can follow up with my team? When I click the `Get from Marketplace` button in the [preview](https://docs-staging.datadoghq.com/bric3/ide-alternate-marketplace-install/developers/ide_integrations/idea/#install-the-datadog-plugin), it seems to open the JetBrains Marketplace as expected.

**Comment by bric3** [comment]
Ah indeed it's there now! Either this was my ad blocker. Or the preview with the latest commit wasn't yet published.

Regardless this is appear to be working.

**Review by buraizu — APPROVED** [review]

**Comment by buraizu** [comment]
@bric3 thank you for your patience, approved!

**Comment by bric3** [comment]
Cool thank you @buraizu

**Pull request merged**
