### PR TITLE
[WEB-3432] Update Code Tabs behavior

### PR DESCRIPTION
**Pull request by aaxzheng**
### What does this PR do?

This makes it so clicking a tab no longer brings you to the top of the screen.
### Motivation

JIRA Ticket: https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3432

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by maycmlee — APPROVED** [review]
Thanks @aaxzheng for this PR! We spot checked other pages with tabs and everything seems to be working as expected. Is this ready to merge?

**Comment by aaxzheng** [comment]
@maycmlee Yeah just moved the logic into an existing event listener for an upcoming fix I'm looking into with the tabs. Should behave exactly the same as the logic you looked at already

**Comment by aaxzheng** [comment]
@maycmlee feel free to merge it in anytime

**Comment by motdde** [comment]
I guess I was slow, 😂.

I discovered the bug some days ago; I should have checked if someone was working on it.

Congrats to @aaxzheng for nailing the PR.

Recording 2023-04-05 at 05 10 47

**Pull request merged**
