### PR TITLE
Remove old 'officially integrating with dd' guide

### PR DESCRIPTION
**Pull request by kmshultz**
This older guide (it's not really a 'guide') seems unnecessary now that there's http://docs.datadoghq.com/guides/integration_sdk. If you concur with removing it, I'll delete the file.

In the docs redesign, we may want to reintroduce this invitation somewhere, i.e. on the main 'Integrations' page, linking to http://docs.datadoghq.com/guides/integration_sdk.

### CODE REVIEW

**Comment by irabinovitch** [comment]
Agreed its not a guide but it seems to have slightly different content than the SDK page.  Could we find a new home for it and and links to the SDK page?

**Comment by jeremy-lq** [comment]
If we keep this guide, linking to and briefly explaining integrations-extras may also make sense. The "Submitting Your integration" bit on the SDK page should also be updated based on recent discussions.

**Comment by technovangelist** [comment]
whats the next step on this one?

**Comment by kmshultz** [comment]
I think we can ignore it until the Docs redesign, which is when I imagine we'll do a lot of refactoring of content.

**Comment by technovangelist** [comment]
so should we kill the pr?

**Comment by kmshultz** [comment]
Sure.

**Pull request closed without merging**
