### PR TITLE
Taka2noda patch 3

### PR DESCRIPTION
**Pull request by taka2noda**
### What does this PR do? What is the motivation?

Add document link for Composite Monitor and improve explanation.

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by drichards-87 — CHANGES_REQUESTED** [review]
Left a small suggestion on wording.

**Comment by taka2noda** [comment]
@drichards-87 Thank you for suggestion! Updated.

**Comment by drichards-87** [comment]
@taka2noda Sounds good! Is this ready to be merged now?

**Comment by taka2noda** [comment]
@drichards-87 Thank you for checking! Yes, please.

**Review by drichards-87 — APPROVED** [review]

**Pull request merged**
