### PR TITLE
Translation Pipeline PR

### PR DESCRIPTION
**Pull request by guacbot**
This auto-generated PR contains the latest completed translation files downloaded from Transifex.
 Preview: https://docs-staging.datadoghq.com/guacbot/translation-pipeline

### CODE REVIEW

**Comment by hestonhoffman** [comment]
I fixed a bunch of errors, but I'm getting this one now:
```
ERROR [include-markdown shortcode] Page error_tracking/issue_states not found
ERROR [include-markdown shortcode] Page error_tracking/default_grouping not found
ERROR [include-markdown shortcode] Page error_tracking/suspect_commits not found
ERROR [include-markdown shortcode] Page error_tracking/explorer not found
ERROR [include-markdown shortcode] Page error_tracking/custom_grouping not found
```
Not sure how to fix this and I don't have time left to track it down now, so I'm passing the torch

**Review by hestonhoffman — APPROVED** [review]

**Review by drichards-87 — APPROVED** [review]

**Review by brooklynebkbk — APPROVED** [review]
build errors have been resolved and no unexpected files being edited

**Pull request merged**
