### PR TITLE
Add logo for Amazon Network Firewall

### PR DESCRIPTION
**Pull request by sarina-dd**
### What does this PR do?
Adds the integration logo for ANF

### Motivation
Currently missing, need to populate docs in integrations page

### Preview
https://docs-staging.datadoghq.com/sarina/amazon-network-firewall/integrations

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by ruthnaebeck — CHANGES_REQUESTED** [review]
This image size must be 200 x 128

**Comment by sarina-dd** [comment]
@ruthnaebeck So strange, it was the large logo when I saved it 😭 I'll fix, thanks for flagging!

**Review by ruthnaebeck — CHANGES_REQUESTED** [review]
Sorry I missed this the first time, but the filename has to be the same as the integrations folder name. So, replace the dashes with underscores. New filename should be `amazon_network_firewall.png`

**Comment by sarina-dd** [comment]
@ruthnaebeck updated the name and size 👍

**Review by ruthnaebeck — APPROVED** [review]

**Pull request merged**
