### PR TITLE
Avoid duplicating the RBAC setup

### PR DESCRIPTION
**Pull request by mfpierre**
### What does this PR do?
Avoid duplicating the RBAC setup

### Motivation
Avoid forgetting or updating the wrong RBAC section

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by cswatt** [comment]
hi @mfpierre! While I'm a big fan of deduplicating, I don't think this page is the best use-case. It'll create more confusion for users than is really ideal. However, to make the difference more clear, we could move the "Instructions for previous Agent and Cluster Agent versions" to a different page, maybe called "Legacy configuration" or something. What do you think?

**Comment by mfpierre** [comment]
@cswatt thanks for the review, I'm open to any suggestion that would allow us to avoid maintaining twice the RBAC list as it's prone to errors, maybe we could keep it as it's today but use some kind of an embed/include mechanism? (didn't look further if it was possible)

**Comment by urseberry** [comment]
Created DOCS-3900 to track Cecilia's review.

**Comment by cswatt** [comment]
Closing in favor of https://github.com/DataDog/documentation/pull/15093/

**Pull request closed without merging**
