### PR TITLE
Update mongodbatlas.md

### PR DESCRIPTION
**Pull request by pierreln-dd**
Issue with link to mongodb atlas

see also /layouts/shortcodes/dbm-mongodb-agent-data-collected.md

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Comment by drichards-87** [comment]
Hi @pierreln-dd. I took a closer look at the PR. From what I can tell, the main issue is that that the link in the [Data Collected section](https://docs.datadoghq.com/database_monitoring/setup_mongodb/selfhosted?tab=standalone#data-collected) is pointing to the Metrics table for the [primary MongoDB integration](https://docs.datadoghq.com/integrations/mongo/?tab=standalone#metrics), and not the metrics for [the MongoDB Atlas integration](https://docs.datadoghq.com/integrations/mongodb_atlas/#data-collected). Can you confirm if my understanding is correct?

**Comment by drichards-87** [comment]
Hi @pierreln-dd. Just to confirm, the main issue is that that the link in the [Data Collected section](https://docs.datadoghq.com/database_monitoring/setup_mongodb/mongodbatlas?tab=replicaset) for MongoDB Atlas is pointing to the [API and Application Keys article](https://docs.datadoghq.com/account_management/api-app-keys/), and not the metrics table for [the MongoDB Atlas integration](https://docs.datadoghq.com/integrations/mongodb_atlas/#data-collected)?

Looking at the [dbm-mongodb-agent-data-collected.md](https://github.com/DataDog/documentation/blob/master/layouts/shortcodes/dbm-mongodb-agent-data-collected.md) shortcode, I can see there's a link without a destination URL. I can add the destination URL, which should be https://docs.datadoghq.com/integrations/mongodb_atlas/#data-collected, correct?

**Comment by pierreln-dd** [comment]
@drichards-87 , I'm open to either, I was just looking to make the simplest edit that fixed the issue. I also wasn't sure what was "best practice" for this kind of case.
Do you want me to make those changes?

**Review by lu-zhengda — APPROVED** [review]

**Comment by drichards-87** [comment]
@pierreln-dd  I went ahead and created a separate PR [25466](https://github.com/DataDog/documentation/pull/25466) that moves the Metrics section outside of the shortcode. Let me know if that works for you. (And also if the links are pointing to the correct/expected URLs.) In the meantime, I'll close this PR in favor of the new one I created.

**Pull request closed without merging**
