### PR TITLE
[cayetano.delgado] fixing datadog logs sink config

### PR DESCRIPTION
**Pull request by jcayetano**
Fixes into the YAML; TOML and JSON config examples for datadog_logs sink

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Awesome, thanks! We had discussed making gzip the default before for that sink. It is a trade-off of throughput and CPU usage vs. bandwidth.

**Review by rtrieu — APPROVED** [review]
LGTM

**Comment by maycmlee** [comment]
Hey @jcayetano! This page was removed in this [PR](https://github.com/DataDog/documentation/pull/16890) because the info was outdated and incorrect, as mentioned in this [comment](https://github.com/DataDog/documentation/pull/16890#issuecomment-1426794244). @silversupreme is currently working on a new doc that would replace this one.

**Comment by jcayetano** [comment]
> 



> Hey @jcayetano! This page was removed in this [PR](https://github.com/DataDog/documentation/pull/16890) because the info was outdated and incorrect, as mentioned in this [comment](https://github.com/DataDog/documentation/pull/16890#issuecomment-1426794244). @silversupreme is currently working on a new doc that would replace this one.

That's fina, shouldn't we remove the link from the menu as well?
https://a.cl.ly/geuO6ByQ

**Comment by maycmlee** [comment]
> That's fina, shouldn't we remove the link from the menu as well? https://a.cl.ly/geuO6ByQ

Ah, thanks, yes missed that one! PR to remove that for now: https://github.com/DataDog/documentation/pull/17024

**Comment by maycmlee** [comment]
@jcayetano I'm closing this PR since the doc no longer exists and a new one is getting published. Thanks!

**Pull request closed without merging**
