### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by edrevo**
### What does this PR do? What is the motivation?
Fix broken links

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Comment by edrevo** [comment]
@DataDog/documentation, I was surprised to find dead links on our docs. Do we have any process in place to avoid dead links? I'm a bit worried that there might be others.

**Comment by edrevo** [comment]
The 404 behavior has disappeared now, so maybe this is something intermittent that only happens during deployments of new versions of the site or something similar. I'm very confused, but I am 100% sure I was getting 404 pages when clicking those links.

**Comment by edrevo** [comment]
here's an image proof to convince myself i'm not hallucinating:
image

**Comment by aliciascott** [comment]
Thanks @edrevo ! Closing this pursuant to https://github.com/DataDog/documentation/pull/21902

**Pull request closed without merging**
