### PR TITLE
Add documentation on how to setup tracer for chiseled containers

### PR DESCRIPTION
**Pull request by vandonr**
### What does this PR do? What is the motivation?
Chiseled containers contain no shell, so we cannot run the usual commands in there.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes
I added some instructions, but they feel a little bit out of place since they are docker commands, while other instructions are just a line of bash.
If you think those instructions belong somewhere else, please advise.

I wrote a [personal blog post](https://medium.com/p/00b1db18f4b9) explaining it in more details.

### CODE REVIEW

**Comment by drichards-87** [comment]
Hi @vandonr. Thanks for submitting this PR. I went ahead and created DOCS-8314. This is a small change, but your question about whether Docker commands should be mixed with Bash commands is valid. So I want to make sure that someone more familiar with the APM tracing docs takes a look at this.

**Review by brett0000FF — APPROVED** [review]
@vandonr - Thanks for adding this content! I agree that the original info was somewhat out of place, so I put it beneath in a new section. Please me know what you think of this change. Thanks!

**Comment by vandonr** [comment]
ok, it is true that those instructions will work for all containers, but copying an empty folder instead of using `mkdir` directly is kind of a hack that is unnecessary in containers that have a shell.

**Comment by brett0000FF** [comment]
> ok, it is true that those instructions will work for all containers, but copying an empty folder instead of using `mkdir` directly is kind of a hack that is unnecessary in containers that have a shell.

@vandonr - Got it. Do you think we could just rename the new section to "Chiseled containers" then to be more specific?

**Pull request merged**
