### PR TITLE
[DOCS-8268] APM FAQ documentation

### PR DESCRIPTION
**Pull request by iadjivon**
### What does this PR do? What is the motivation?

This PR is adding a new page for a list of APM's frequently asked questions along with the solutions for them.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

Documentation Editorial Review: https://datadoghq.atlassian.net/browse/DOCS-8268

### CODE REVIEW

**Comment by brett0000FF** [comment]
@iadjivon - Thanks for submitting this PR! I am going to review it early next week for you.

I did a quick glance and noticed that it appears you pulled some extra files into this PR? There is a duplicate of the FAQ page named "~" and there are a couple changes to security files. Think you could revert those? Thanks!

**Comment by brett0000FF** [comment]
@iadjivon - Thanks again for creating this content! I just have a couple questions for you about it:

* How strongly do you feel about this being a brand-new page, instead of adding the content to our existing Troubleshooting page? I want to be mindful about users having multiple places to search for answers.
* Are these issues particularly common from your perspective? If so, that might justify a separate quick-reference page.

Thanks! Just wanted to pick your brain a bit.

**Comment by iadjivon** [comment]
Hi Brett, 
Thanks for your help on this PR and apologies for the delay. To answer your questions: 

> How strongly do you feel about this being a brand-new page, instead of adding the content to our existing Troubleshooting page? I want to be mindful about users having multiple places to search for answers.

The APM Product team looked through metabase for traffic to the Troubleshooting page and preferred this to be it's own header. 

> Are these issues particularly common from your perspective? If so, that might justify a separate quick-reference page.
The solutions team very often receive these questions from clients and would like to house this in a public documentation to make it easier for clients to find these answers. 

Let me know if you have any questions!

**Comment by iadjivon** [comment]
> @iadjivon - Thanks for submitting this PR! I am going to review it early next week for you.
> 
> I did a quick glance and noticed that it appears you pulled some extra files into this PR? There is a duplicate of the FAQ page named "~" and there are a couple changes to security files. Think you could revert those? Thanks!

Thanks for the note, I deleted those files, but let me know if this is not reflected on your end.

**Review by brett0000FF — APPROVED** [review]

**Pull request merged**
