### PR TITLE
carlos/iconfont-update

### PR DESCRIPTION
**Pull request by csantosdd**
### What does this PR do?
- adds the websites-modules iconfont to docs
- adds iconfont to the following areas
  - homepage nav tiles/cards
  - main sidenav (on search results)
  - mobile sidenav (hamburger menu)
- updates some icons in nav tiles and sidebar

### Motivation
- iconfont better depending on who you ask
- loading one font file instead of more SVGs
- utilizing shared resources from websites-modules repo
- https://datadoghq.atlassian.net/browse/WEB-1709
- looks better?

### Preview
https://docs-staging.datadoghq.com/carlos/iconfont-update/

### Additional Notes
- [ ] check to ensure there's only minimal diff between preview and prod. some diffs like sizing horizontally are inevitable due to the rendering diffs between a font vs an inline SVG

this change is a three-prong PR between `websites-modules`, `corp-hugo`, and `documentation`. i will be coordinating the merges from websites-modules first since the consuming sites need to have their `go.mod` files cleared and respective cloudfront cache purged for the fonts directories.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.

### CODE REVIEW

**Review by ruthnaebeck — CHANGES_REQUESTED** [review]
I see this on the front page:
image

**Comment by csantosdd** [comment]
@ruthnaebeck derek caught this and it's fixed w/ https://github.com/DataDog/documentation/pull/11633/commits/d20978a75279bff74d11feb08ac19cc3db74a6ec

**Review by angli0328 — COMMENTED** [review]
the new iconfont looks great!! just wanted to highlight that the icon for CSPM on the main nav is not consistent with what is currently live on corp. could we update that in this PR too?
on doc:
Screen Shot 2021-09-09 at 4 16 07 PM
on corp:
Screen Shot 2021-09-09 at 4 16 16 PM

**Review by ruthnaebeck — APPROVED** [review]
👍  for docs

**Comment by csantosdd** [comment]
@angli0328 got the product dropdown menu to use iconfont and also have updated all the menu items for product in EN, FR, and JA 👍

**Review by angli0328 — APPROVED** [review]

**Pull request merged**
