### PR TITLE
Moore/aws lambda

### PR DESCRIPTION
**Pull request by themsquared**
Just a quick fix on the lambda code page and a CSS update for <code> blocks. This may impact other pages with multiple lines of code though so it'd be smart to review before merging.

### CODE REVIEW

**Comment by kmshultz** [comment]
@themsquared Thanks submitting this.

Actually, instead of `<code>`,  let's use backticks for in-line code and ~~~ for multi-line code blocks, e.g.:

~~~
unix_epoch_timestamp = int(time.time())
value = 42
...
~~~

(see https://kramdown.gettalong.org/quickref.html#code-blocks)

This way, we should get multi-line code - with breaks - and we can avoid messing with CSS.

Thanks again!

**Comment by themsquared** [comment]
Works for me.  Just want to make the multi-lines readable 👍

**Comment by kmshultz** [comment]
@themsquared Yep, thanks for spotting it! If you don't mind updating it as I described, I'll merge. Otherwise we can close this and I'll fix it in a different PR - it's up to you.

**Comment by themsquared** [comment]
Updated. Please review and merge if good to go.

**Comment by kmshultz** [comment]
@themsquared Looks good - thanks again!

**Pull request merged**
