### PR TITLE
[aws] Note lambda perms

### PR DESCRIPTION
**Pull request by peterashwell**
@DanielLanger this OK?

### CODE REVIEW

**Comment by DanielLanger** [comment]
@peterashwell aren't there more permissions?

image

**Comment by irabinovitch** [comment]
@peterashwell @DanielLanger did we determine if more is needed here before merging?

**Comment by DanielLanger** [comment]
No, let me look today @irabinovitch

**Comment by irabinovitch** [comment]
@peterashwell @DanielLanger ping?

**Comment by DanielLanger** [comment]
@irabinovitch good to merge

**Pull request merged**
