### PR TITLE
Removing irc references

### PR DESCRIPTION
**Pull request by l0k0ms**
https://github.com/DataDog/documentation/issues/1593

### CODE REVIEW

**Comment by l0k0ms** [comment]
@jeremy-lq we could add the link to the slack channel in the footer of the doc? So it's available on all doc page.

**Comment by l0k0ms** [comment]
@jeremy-lq  Slack link is already in the help section. https://docs.datadoghq.com/help/#slack

LGTM ?

**Comment by jeremy-lq** [comment]
Possible we should just link to the help section in that case, but I'll leave that decision to you. Approving so you can merge whichever you decide.

**Comment by l0k0ms** [comment]
@jeremy-lq good idea 👍  linking to help page instead.

**Pull request merged**
