### PR TITLE
scraping content from int-core

### PR DESCRIPTION
**Pull request by l0k0ms**
### What does this PR do?

Creates a function during builds to scrap content from here:

https://github.com/DataDog/integrations-core/tree/master/docs/dev

And displays it here: `/content/developers/integrations`

In order to document new check creation for agent 6

### Motivation

Pushing knowledge to the edges have been one of the goal of this documentation 2.0, allowing a better consistency across all knowledge displayed by DD. And reducing the complexity of documentation contributions. 

The idea here is the same as the one implemented for the integrations documentation pages. The documentation for integrations-core related topics should be integrated into the integrations core repo directly, allowing developers to include doc updates in their contributing process.

### Preview link

* https://docs-staging.datadoghq.com/gus/scrap-content/developers/integrations/

### TO DO

* [x] Update the doc content to match contributing guidelines of the doc
* [x] Add internal links on the integrations repo doc
* [x] Update main nav / doc titles to make them match
* [x] Fixes broken links in the French version fo the doc

### CODE REVIEW

**Comment by l0k0ms** [comment]
This PR should be merged first: https://github.com/DataDog/integrations-core/pull/1595

**Comment by phrawzty** [comment]
Speaking from a organisational standpoint, we'll need to re-factor the Dev Tools section in general, as this definitely overlaps (and in some cases, collides) with existing documentation. That said, we needed to re-factor anyway, so this PR is a good catalyst for that work. 🙂 

Let's take a quick look over the incoming documentation before we merge. No deep-diving - just enough to put us in a good spot to iterate going forward. In any case, thanks @masci and @l0k0ms for your hard work on this content and functionality. 💯  Looking forward to merging this asap!

**Comment by jeremy-lq** [comment]
@masci This workflow look good to you?

**Comment by masci** [comment]
@jeremy-lq LGTM, can't wait to have the new docs published!

**Pull request merged**
