### PR TITLE
Java Tracer 0.14.0 Release Doc update

### PR DESCRIPTION
**Pull request by realark**
Small doc change for java manual tracer install for the 0.14.0 release.

Preview Link https://docs-staging.datadoghq.com/ark/java-tracer-0.14.0-release/tracing/setup/java/#custom-instrumentation-examples

### CODE REVIEW

**Comment by phrawzty** [comment]
> for the 0.14.0 release

I'm not familiar with the release schedule; should this be merged now, or should we wait for the 0.14.0 release?

**Comment by iFallUpHill** [comment]
@phrawzty 0.14.0 was released. Can we pull this change into the other pending APM PR? #2909 @l0k0ms

**Comment by realark** [comment]
@iFallUpHill Looks like that PR was just merged. I rebased from master and resolved the conflicts.

**Comment by realark** [comment]
Thanks for the edits @cswatt!

**Pull request merged**
