### PR TITLE
content/en/tracing/trace_collection/library_config/go.md: partial flushing configuration

### PR DESCRIPTION
**Pull request by katiehockman**
### What does this PR do?

Adds documentation for the Go Tracer's configuration of partial flushing.

### Motivation

The Go Tracing library now supports partial flushing.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by brett0000FF — APPROVED** [review]
LGTM! Ping me when this is ready if you need me to merge.

**Comment by katiehockman** [comment]
The code is now released!

**Pull request merged**
