### PR TITLE
Fix caps issues in config

### PR DESCRIPTION
**Pull request by austinchen15**
### What does this PR do?

Lowercases the transform components in the config to sidestep this bug: https://datadoghq.atlassian.net/browse/OPB-985

Besides, the all caps transform looks somewhat inconsistent anyways.

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by spencergilbert — COMMENTED** [review]
Using caps in the component name causes issues?

**Comment by austinchen15** [comment]
> Using caps in the component name causes issues?

https://datadoghq.atlassian.net/browse/OPB-985

Yeah we discovered this last week when the UI side wasn't reporting events flowing through component (visually)

**Comment by austinchen15** [comment]
Heads up @sghall: this will require you to pull the config again into the ui code.

**Review by spencergilbert — APPROVED** [review]
Ah, problem on the backend - I thought this was a "OPW fails with caps" which would have surprised me.

**Review by estherk15 — APPROVED** [review]
Thanks @austinchen15 is this ready to merge?

**Review by pront — APPROVED** [review]

**Comment by austinchen15** [comment]
> Thanks @austinchen15 is this ready to merge?

Yes, ready to merge! Thanks

**Pull request merged**
