### PR TITLE
update beta callout - [WEB-3063]

### PR DESCRIPTION
**Pull request by StefonSimmons**
### What does this PR do?

creates `{{ callout }}` shortcode to replace `{{ beta-callout }}`
enables ability to edit header in `{{ callout }}` and `{{ beta-callout }}` shortcode.

Note: we are leaving the `beta-callout` shortcode here since some integration files are using it

### Motivation

https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3063

### Preview

there should be no visible difference - only the ability to configure the header on callouts
https://github.com/DataDog/documentation/pull/16558#issuecomment-1405207673

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by maycmlee** [comment]
Thanks Stefon! Created [DOCS-4752](https://datadoghq.atlassian.net/browse/DOCS-4752) for review.

**Review by apigirl — APPROVED** [review]

**Review by devindford — APPROVED** [review]
LGTM as well!

**Comment by eho1307** [comment]
Does this affect any Marketplace docs?

**Comment by StefonSimmons** [comment]
> Does this affect any Marketplace docs?

Hi @eho1307 no. I'm closing this PR

**Pull request closed without merging**
