### PR TITLE
Update the IP allowlist example

### PR DESCRIPTION
**Pull request by anthony-dgx**
### What does this PR do? What is the motivation?
Updating the screenshot example to showcase a Public IP (instead of 127.0.0.1).
 

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by pcarioufr — COMMENTED** [review]
195.13.233.0/24 is correct, but let's use 195.13.233.10 instead of 195.13.233.0 (the subnet ID) for the single IP example.

**Review by aliciascott — CHANGES_REQUESTED** [review]
Hi @anthony-dgx this looks good to me, but can you re-add the old image to the branch? We like to leave those as there is a slight delay with the translation process for other languages and this way it won't show a broken image in the meantime thanks! Also looks like @pcarioufr left a comment for you :) Let me know when it's updated and I'll review again and merge !

**Comment by anthony-dgx** [comment]
Hi @aliciascott 👋 

Thanks for your comment and for the documentation, I didn't know about it. I just restored the initial file and updated the name of the new one. 

PR is ready for review 👌 

Thanks in advance!

**Comment by aliciascott** [comment]
Hi @anthony-dgx one more thing you also have to add the new image name to the markdown file so in `/content/en/account_management/org_settings/ip_allowlist.md/` you'll have to update Line 72 : `{{< img src="account_management/org_settings/add_ip.png" alt="Screenshot showing a dialog box titled Add IP to allowlist" >}}` to be `{< img src="account_management/org_settings/add_ip_2.png" alt="Screenshot showing a dialog box titled Add IP to allowlist" >}}`

**Comment by anthony-dgx** [comment]
Oh sorry, you're right @aliciascott! I did it! Thanks a lot!

**Review by aliciascott — APPROVED** [review]
thanks looks good!

**Pull request merged**
