### PR TITLE
Add host benchmarks to CSM misconfiguration docs

### PR DESCRIPTION
**Pull request by janine-c**
### What does this PR do? What is the motivation?

Small update to add host benchmarks to our page on CSM misconfiguration compliance rules.

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### CODE REVIEW

**Review by lucasdmaley — APPROVED** [review]
Looks great!

**Review by aliciascott — APPROVED** [review]
Hi @janine-c looks good! Just a small suggestion but approved

**Comment by janine-c** [comment]
Great suggestions, thank you @aliciascott !

**Pull request merged**
