### PR TITLE
Add screenshot and Validation to capistrano integration doc

### PR DESCRIPTION
**Pull request by kmshultz**
@jyee Please review.

### CODE REVIEW

**Comment by kmshultz** [comment]
By the way, this was prompted by https://github.com/DataDog/dogapi-rb/issues/122.

**Comment by jyee** [comment]
Looks good other than headings. They should start with H3 (you're currently doing H2) or H1 (if you set `newhlevel: true` in the header) and we can remove the IDs on them. IDs will get auto-generated by nanoc along with the sidebar TOC.

**Comment by kmshultz** [comment]
@jyee Got it - fixed.

**Comment by jyee** [comment]
LGTM!

**Pull request merged**
