### PR TITLE
DOCS-8240 Add Tag Explorer Documentation

### PR DESCRIPTION
**Pull request by alai97**
### What does this PR do? What is the motivation?

Adds a doc page about the Tag Explorer in the Cloud Cost Management section.

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Review by brett0000FF — APPROVED** [review]
Great! LGTM. 🚀

**Comment by goeln** [comment]
Hey @alai97 ! I know we paused this because we were going to make some changes, those changes are now in progress, will keep you up to date

**Comment by goeln** [comment]
Overall looks good, can we take the screenshots from the demo org? for any cost providers that aren't showing up in demo org, can we truncate the screenshot to just show tags that have a description? the rest of the tags in org 2 i'd rather not have in public docs :)

**Comment by goeln** [comment]
also, all integrations are now public beta if you can update these docs tor reflect that!!

**Pull request merged**
