### PR TITLE
Add `auto_multi_line_default_match_threshold` example

### PR DESCRIPTION
**Pull request by estherk15**
### What does this PR do? What is the motivation?

- Add example for `auto_multi_line_default_match_threshold`
- [DOCS-7174](https://datadoghq.atlassian.net/browse/DOCS-7174)

### Merge instructions

**Do not merge**

### Additional notes

[DOCS-7174]: https://datadoghq.atlassian.net/browse/DOCS-7174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by aliciascott — APPROVED** [review]
looks good

**Comment by carlosroman** [comment]
This looks great. Just wondering if we should mention the threshold can be obtained from the output of `agent status` command?

**Comment by estherk15** [comment]
> This looks great. Just wondering if we should mention the threshold can be obtained from the output of `agent status` command?

Thanks for taking a look @carlosroman. Yes, I can add that information. Do you know if this is configuration that is also available for [Docker and Kubernetes](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile#automatic-multi-line-aggregation)?

**Comment by carlosroman** [comment]
> Thanks for taking a look @carlosroman. Yes, I can add that information. Do you know if this is configuration that is also available for [Docker and Kubernetes](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=configurationfile#automatic-multi-line-aggregation)?

Yes, it is available in all instances of the Agent. For Docker and Kubernetes you need to pass it as an environment variable, `DD_LOGS_CONFIG_AUTO_MULTI_LINE_DEFAULT_MATCH_THRESHOLD`.

**Pull request merged**
