### PR TITLE
Adding AWS Route 53 integration

### PR DESCRIPTION
**Pull request by jyee**
https://trello.com/c/UpKCVJ7w/913-documentation-route53

### CODE REVIEW

**Comment by technovangelist** [comment]
looks good. not the most exciting image though.

**Comment by jyee** [comment]
Yeah, I guess I can do a bunch of random health checks to give it more variety.

**Comment by irabinovitch** [comment]
@jyee LGTM. Lets merge and we can come back with better images later?

**Comment by jyee** [comment]
Yes, of course.

**Pull request merged**
