### PR TITLE
Fix Kubernetes manifests url for the Datadog cluster agent RBAC

### PR DESCRIPTION
**Pull request by L3n41c**
### What does this PR do?

Fix Kubernetes manifests url for the Datadog cluster agent RBAC.

### Motivation

Kubernetes manifests files are now generated: DataDog/datadog-agent#5436
The old ones will be removed with DataDog/datadog-agent#5606

The URL in the documentation should have been updated by #7542 but it seems some changes were reverted.

### Preview link

https://docs-staging.datadoghq.com/lenaic/fix_k8s_manifests_location/agent/cluster_agent/setup/?tab=secret
Check preview base path using the URL in details in `preview` status check.

### CODE REVIEW

**Comment by Simwar** [comment]
Step 3 must be also changed with the new DCA manifest: https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/manifests/cluster-agent/cluster-agent-deployment.yaml

Step 3 link: https://github.com/DataDog/documentation/blob/a6a8eb459fc062d9f931224a0b8e32b7cfd3eb1b/content/en/agent/cluster_agent/setup.md#step-3---create-the-cluster-agent-and-its-service

**Comment by apigirl** [comment]
I looked into where this got reverted - I think it was a bad merge conflict fix. Thanks for updating again @L3n41c!

**Comment by L3n41c** [comment]
Sure !
It seems there are other links which have been reverted to the old value.
Let me fix all of them.

**Comment by L3n41c** [comment]
@Simwar @apigirl : I have reviewed the whole cluster agent doc.

**Pull request merged**
