### PR TITLE
Adjust best practices for recommended monitors

### PR DESCRIPTION
**Pull request by estherk15**
### What does this PR do? What is the motivation?

- Add best practices and examples for **Title** and **Description** of recommended monitors

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Review by buraizu — APPROVED** [review]
Nice, looks good overall and approved! 

With that said, I just wanted to point out that the `Description` in the screenshot of the "well-defined monitor" below your update is out of compliance with the Description guidelines you're providing in the table -- looks like it would fall under the `Needs revision` category. I'll let you decide whether to merge this now or update the screenshot first

**Comment by estherk15** [comment]
> Nice, looks good overall and approved!
> 
> With that said, I just wanted to point out that the `Description` in the screenshot of the "well-defined monitor" below your update is out of compliance with the Description guidelines you're providing in the table -- looks like it would fall under the `Needs revision` category. I'll let you decide whether to merge this now or update the screenshot first

Thanks @buraizu! I didn't even pay attention to that image!

**Comment by eho1307** [comment]
Hi! was there a reason we remove the image of the well defined monitor?

**Comment by eho1307** [comment]
> > Hi! was there a reason we remove the image of the well defined monitor?
> 
> Hi @eho1307, the image doesn't follow the new best practices for monitor title and descriptions. I think the directions are pretty clear on how to create a monitor and what is and isn't a well-defined monitor. I think that might be enough. Let me know if you disagree!

Noted and approved from my end.

**Pull request merged**
