### PR TITLE
perf improvements

### PR DESCRIPTION
**Pull request by davidejones**
### What does this PR do?

- partialcache header, footer, apinav, nav
- remove debug logs on preview hugo deploy
- dump logs to file instead of console
- use cpu count for download pool instead of hardcoded

### Motivation

General speed improvements

### Preview

- Need to spot test as many pages as we can and check the header/footer/nav/apinav all looks good. 
https://docs-staging.datadoghq.com/david.jones/perf/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by bgdeutsch — COMMENTED** [review]
Looks like the API side nav isn't expanding as I would expect: https://docs-staging.datadoghq.com/david.jones/perf/api/latest/logs/

**Comment by davidejones** [comment]
> Looks like the API side nav isn't expanding as I would expect: https://docs-staging.datadoghq.com/david.jones/perf/api/latest/logs/

Thanks. I removed this for now as it varies per page so it didn't seem much point in caching

**Review by bgdeutsch — APPROVED** [review]
LGTM 👍

**Review by apigirl — APPROVED** [review]
this lgtm! I spot checked a bunch of pages too. Feel free to merge when you are ready

**Pull request merged**
