### PR TITLE
Converting agent proxy instructions to use tabs

### PR DESCRIPTION
**Pull request by nicholas-devlin**
### What does this PR do?

Restructure proxy info into tabs to make it more clear

### Motivation

Request from @henrydoan 

### Preview

https://docs-staging.datadoghq.com/nicholas.devlin/agent-proxy-tabs/agent/proxy/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by jtappa** [comment]
Hey @nicholas-devlin, just want to check: did you have confirmation from the Agent team to remove Agent 5 docs?

**Comment by nicholas-devlin** [comment]
No this should have been marked as a draft, I'm still working on with with some other team members.

**Comment by jtappa** [comment]
Ok, cool! I just added the WIP label, you can remove it whenever you're ready for us to do a review. 😃

**Comment by apigirl** [comment]
Closing this for now after a discussion with Nicholas, but may reopen later if needed!

**Pull request closed without merging**
