### PR TITLE
[To merge on May 8th] Update Log documentation with Autodiscovery

### PR DESCRIPTION
**Pull request by NBParis**
### What does this PR do?
Add autodiscovery setup to the log documentation

### Motivation
The feature is released in agent 6.2

### Preview link
https://docs-staging.datadoghq.com/nils/autodiscovery/

### CODE REVIEW

**Comment by NBParis** [comment]
Thanks @l0k0ms For the update

**Comment by NBParis** [comment]
@xvello Indeed we do not support yet Kubernetes Annotation which is why we updated only the container label section.

As you said, once we use a unified AD in 6.3 we will be able to update all the different Autodiscovery mechanism.

**Comment by jeremy-lq** [comment]
6.2 has been released. @NBParis @xvello is this PR ready to be merged in its current state?

**Comment by xvello** [comment]
👍

**Pull request merged**
