### PR TITLE
[DOCS-5031] Update obs reference

### PR DESCRIPTION
**Pull request by davidejones**
### What does this PR do?

Updates the reference schemas and makes a change to pull the header from docs::label over description1

### Motivation

Updating

### Preview
https://docs-staging.datadoghq.com/david.jones/obs-update/observability_pipelines/reference/sources/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by buraizu** [comment]
Thanks, created DOCS-5031 to review

**Review by maycmlee — APPROVED** [review]
Checked the preview and it LGTM, thanks!

**Comment by maycmlee** [comment]
@davidejones can you let me know when this can be merged?

**Comment by devindford** [comment]
LGTM

**Review by devindford — APPROVED** [review]

**Comment by davidejones** [comment]
@maycmlee feel free to merge when ready!

**Pull request merged**
