### PR TITLE
CSM without infra monitoring - apply Rajat's edits

### PR DESCRIPTION
**Pull request by janine-c**
### What does this PR do? What is the motivation?

Follow up to https://github.com/DataDog/documentation/pull/26381

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### CODE REVIEW

**Review by estherk15 — APPROVED** [review]
Left an optional suggestion, approved!

**Review by rajat-luthra-ddog — APPROVED** [review]
Assuming this page will only list for AWS and not Azure and GCP in this PR.

**Comment by janine-c** [comment]
Renaming branch so merge works this time 🙃

**Pull request closed without merging**
