### PR TITLE
Update announcement banner

### PR DESCRIPTION
**Pull request by csantosdd**
### What does this PR do?
- updates the announcement banner w/ DASH roundup

### Motivation
requested by Leo Schramm

https://docs-staging.datadoghq.com/carlos/update-announcement-banner-post-dash/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by csantosdd** [comment]
This PR should be merged in after the Dash Roundup Blog post goes live (~11:30am on Wed 10/19)

**Review by nsollecito — APPROVED** [review]

**Comment by csantosdd** [comment]
@jtappa can i just ask what's the `scallion pancakes` label 👀

**Comment by csantosdd** [comment]
@apigirl i'm just waiting for keynote to end and then this can be merged in!

**Comment by urseberry** [comment]
> @jtappa can i just ask what's the `scallion pancakes` label 👀

It's the docs team's secret label for Dash content.

**Pull request merged**
