### PR TITLE
DOCS-9343 - Update containers billing

### PR DESCRIPTION
**Pull request by cswatt**
### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### CODE REVIEW

**Review by AntoinePr — APPROVED** [review]

**Review by drichards-87 — APPROVED** [review]
Approved. Also noting that the PR was removed from the merge queue. I'm not sure if that was intentional or not, so I'll let you re-add it to the queue.

**Pull request merged**
