### PR TITLE
unify upstream and downstream service remapping

### PR DESCRIPTION
**Pull request by zARODz11z**
### What does this PR do?

Document Upstream and Downstream service/peer service mapping in one place for serverless as described in https://docs.datadoghq.com/tracing/trace_collection/library_config/
and https://docs.datadoghq.com/tracing/guide/inferred-service-opt-in/?tab=ruby#peer-service-mapping
### Motivation

SVLS-3520

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by zARODz11z** [comment]
TODO: include SC showcasing upstream and downstream service mapping
Then showcase DD_PEER_SERVICE_MAPPING (still trying to get this working)

**Comment by zARODz11z** [comment]
I'd like to add sc of it working in all runtimes but unfortunately the implementation differs from each tracer (java,ruby, py, js, dotnet, and go)

JS was the easiest to get working so I included that screenshot although I don't see it rendered in the docs preview

**Comment by cswatt** [comment]
Created DOCS-6225 to review

**Comment by zARODz11z** [comment]
the logic is rather confusing and changes between languages as each tracer (py, js, java …) does it slightly different so I thought sc would help. I'm also probably gonna have to reach out to each tracer team to confirm some things/work out some bugs

**Review by cswatt — APPROVED** [review]

**Pull request merged**
