### PR TITLE
Update oauth_for_integrations.md

### PR DESCRIPTION
**Pull request by dd-dominic**
Update OAuth publishing flow instructions.

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Review by emarsha94 — APPROVED** [review]

**Review by neko-dd — APPROVED** [review]

**Review by eho1307 — APPROVED** [review]
Thanks for adding this!

**Comment by eho1307** [comment]
Hey @neko-dd could you help us merge this? We don't have the correct persmissions

**Comment by neko-dd** [comment]
I can merge.

In the future, if you want things merged, you can check the box in the description. :)

**Comment by dd-dominic** [comment]
@neko-dd do you know what may be causing the synthetics check to fail?

**Comment by neko-dd** [comment]
That one I can merge without it passing. The preview is a problem though, I do need that to pass.

**Pull request merged**
