### PR TITLE
Unifies shortcode delimiters

### PR DESCRIPTION
**Pull request by bgdeutsch**
### What does this PR do?
- Replaces most instances of {{% shortcode %}} with {{< shortcode >}}
- Updates tabs.html shortcode to have the markdownify hugo pipe 

Note that pure markdown shortcodes, such as `dbm-sqlserver-before-you-begin.md`, still need to have the `{{% %}}` delimiters **unless they are nested inside a tabs shortcode**.   I will update internal documentation about this change.

We will likely want to temporarily disable the translation pipeline syncing when this is ready to be released as to the pipeline will see these changes and send them all to Transifex to be translated.

### Motivation
There has long been issues in Hugo mixing the two shortcode delimiters (`{{% %}}` and `{{< >}}`) when they are nested.  Recent work to overhaul the docs search functionality uncovered a particularly challenging Hugo bug that doesn't appear to have a different workaround, so it seemed an opportune time to finally update our shortcodes.

### Preview
This needs a thorough site-wide QA, with focus on shortcodes (particularly, tabs).   All content should render correctly - there should be no plain text markdown.

https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/
https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/api/latest
https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/integrations
https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/account_management/rbac/permissions/

Check pages that have pure markdown shortcodes ie:
https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/database_monitoring/setup_sql_server/rds/?tab=windowshost

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by djmitche — APPROVED** [review]
👍🏽 content/en/agent/proxy.md

**Review by devindford — APPROVED** [review]
Checked a majority of pages and clicked through tabs on each one. No console errors and all views (mobile, desktop, tablet) were all working as expected.

**Comment by urseberry** [comment]
Docs review on DOCS-4066

**Comment by hestonhoffman** [comment]
I'm seeing errors a regular `make` build. These don't fail a local build, but these kinds of errors do usually cause the production pipeline to fail. Looks like the issue is with the link-checker: 
```log
Duplicated reference: [2]: https://slack.com/apps/A0F7XDT7F-datadog-legacy
Duplicated reference: [3]: https://app.datadoghq.com/account/settings#integrations/slack
Duplicated reference: [4]: https://docs.datadoghq.com/monitors/notifications/?tab=slackintegration#notification
Duplicated reference: [5]: https://docs.datadoghq.com/events/#notifications
Duplicated reference: [6]: https://www.datadoghq.com/blog/datadog-slack-app/
Duplicated reference: [7]: https://docs.datadoghq.com/help/
Duplicated reference: [1]: https://docs.datadoghq.com/help/
Duplicated reference: [2]: http://slack.com/account/settings
Duplicated reference: [3]: https://api.slack.com/methods/usergroups.list
Duplicated reference: [4]: https://docs.datadoghq.com/monitors/notifications/
Duplicated reference: [5]: https://api.slack.com/scopes
[31mERROR[0m: Some references are duplicated.
[31mERROR[0m: There was an issue processing a section for file: ../dogweb/integration/slack/README.md
```

**Comment by hestonhoffman** [comment]
Weird that it didn't fail the preview, but here is an example of the output: https://docs-staging.datadoghq.com/brian.deutsch/shortcodes/integrations/slack/

**Review by hestonhoffman — APPROVED** [review]
I ran a build and took a lot at some more complex files on the preview and they're looking good now

**Pull request merged**
