### PR TITLE
[service discovery] document using annotations instead of a config store

### PR DESCRIPTION
**Pull request by hkaj**
should wait for agent 5.11

### CODE REVIEW

**Comment by irabinovitch** [comment]
@jyee Can you check if this is still needed given your recent updates in https://github.com/DataDog/documentation/pull/1063 ?

**Comment by jyee** [comment]
@irabinovitch @hkaj Correct, I think all of this is covered in the recent update from #1063 which was merged earlier today. See http://docs.datadoghq.com/guides/servicediscovery/#configuration-templates-with-kubernetes-annotations

That said, the new update could be improved by adding a note that this applies to agent versions 5.11 or higher and could clarify a bit more that sd_config_backend and other etcd/consul vars should be commented out (especially since the k8s section is below the etcd/consul section). I'll add a trello card for these and make the updates soon.

**Comment by irabinovitch** [comment]
@hkaj Are you happy with the state of the other PRs? Can we close this one?

**Comment by hkaj** [comment]
Yes, all good. I didn't see your PR before @jyee. It's great, thanks!

**Pull request closed without merging**
