### PR TITLE
(developers) Rename IDE integrations

### PR DESCRIPTION
**Pull request by hestonhoffman**
### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Review by albertvaka — APPROVED** [review]
LGTM from the IDE ~integrations~ plugins team.

**Comment by hestonhoffman** [comment]
Lots of broken links - I'll figure out what's going on there

**Comment by hestonhoffman** [comment]
> Lots of broken links - I'll figure out what's going on there

fixed

**Review by buraizu — APPROVED** [review]
LGTM

**Pull request merged**
