### PR TITLE
WEB-883 update ja copy

### PR DESCRIPTION
**Pull request by zbayoff**
# What does this PR do?
updated Footer copy to match corpsites.

### Motivation
https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?assignee=5d4b49d50fa6d40d14fc7b11&selectedIssue=WEB-883

### Preview
http://docs-staging.datadoghq.com/zach/update-footer-copy

### CODE REVIEW

**Comment by nsollecito** [comment]
@zbayoff Looks like the Solutions drop-down is blank.. can you take a look?

**Comment by zbayoff** [comment]
@nsollecito sorry, can you post a screen video? I don't see the issue.

**Comment by nsollecito** [comment]
@zbayoff https://share.getcloudapp.com/2NujzN1n

**Comment by nsollecito** [comment]
this is also happening - https://share.getcloudapp.com/4guJKgb7#

**Comment by zbayoff** [comment]
@nsollecito I've fixed the solutions menu. I dont see the issue  with the white space under the footer though.

**Comment by nsollecito** [comment]
@zbayoff the CTA is still pushing to a second line in the nav and overlapping the body but it's like that on live currently too

**Comment by zbayoff** [comment]
@nsollecito yeah this is a known issue, a limitation due to our design. I can try and address in a separate card and get guidance from Brand Design.

**Review by stanleegoodspeed — APPROVED** [review]

**Review by apigirl — APPROVED** [review]

**Pull request merged**
