### PR TITLE
fixes example yaml errors on JMX integration docs

### PR DESCRIPTION
**Pull request by matthewmain**

### CODE REVIEW

**Comment by technovangelist** [comment]
Im all for clarifying, but there isn't a need for those indents is there? does the agent error on that? I believe its valid YAML.

**Comment by matthewmain** [comment]
We received a complaint about this, and we’re seeing that in a parser the present yaml is producing null values. For example:

conf:
- include:
  domain: org.apache.cassandra.db

is yielding:

{
  "conf": [
    {
      "domain": "org.apache.cassandra.db", 
      "include": null
    }
  ]
}
Am I overlooking something?

**Comment by technovangelist** [comment]
ahh, yes, you are right. I misread what that was doing

**Comment by matthewmain** [comment]
cool, thanks!

**Pull request merged**
