### PR TITLE
Add comma to json at _index.md

### PR DESCRIPTION
**Pull request by julinvictus**
### What does this PR do? What is the motivation?
There's a comma missing in the json object attached to the curl command example
https://docs.datadoghq.com/dora_metrics/?tab=apicurl#change-failure-rate

### Merge instructions

- [x] Please merge after reviewing

### CODE REVIEW

**Review by drichards-87 — APPROVED** [review]

**Comment by drichards-87** [comment]
@julinvictus Looks good to me. But I see you added @calvarjorge as a reviewer as well. I'll wait for them to approve before I merge the PR.

**Comment by julinvictus** [comment]
@drichards-87, synth tests are failing every time I try to re-run, I created the PR via UI, could that be the reason? If not, any clue?

**Comment by drichards-87** [comment]
@julinvictus It's because the branch name doesn't include a forward slash (which we use as a key to build the staging preview off of). If you rename the branch, the CI checks should pass. But this is also a very small change, so I'm comfortable merging it without the checks passing.

**Comment by julinvictus** [comment]
@drichards-87 ok, you're welcome to merge it then. The other reviewers were automatically added to the PR.

**Pull request merged**
