### PR TITLE
Fix PUT Endpoint to Follow RESTful Standards and Resolve 405 Method Not Allowed Error

### PR DESCRIPTION
**Pull request by moko-poi**
### What does this PR do? What is the motivation?
This PR fixes the PUT endpoint in the Notes API by updating it to follow RESTful standards. The previous implementation caused a 405 Method Not Allowed error. This change moves the resource ID to the URI path, which resolves the error and aligns the API with RESTful design principles.

### Merge instructions
Please merge after reviewing the updated endpoint and confirming the fix.

### Additional notes
Before the change, the PUT request returned a 405 error. After the update, it now returns a 200 success response with the updated note.

**Before:**
Request:
`curl -X PUT 'BASE_DOMAIN:8080/notes?id=1&desc=UpdatedNote'`

Response:
`405 Method Not Allowed`

**After:**
Request:
`curl -X PUT 'BASE_DOMAIN:8080/notes/1?desc=UpdatedNote'`

Response:
```
{"id":"1","description":"UpdatedNote"}
200 OK
```

### CODE REVIEW

**Review by aliciascott — APPROVED** [review]
Thank you @moko-poi for the addition!

**Comment by aliciascott** [comment]
Hi @moko-poi I actually am un-able to merge this as this PR was created from a forked branch of the Docs repo called `moko-poi`. Can you close this PR And create a new one directly from the [documentation repo](https://github.com/DataDog/documentation)?

**Comment by moko-poi** [comment]
Hi @aliciascott 

Thank you for your feedback! I attempted to push the changes directly to the DataDog/documentation repository as you suggested, but I encountered a permission error. It appears that I don't have the necessary rights to push changes directly to the repository.

**Comment by moko-poi** [comment]
@aliciascott 
This PR was already created by forking the repository and creating a branch named fix/update-put-endpoint-to-restful (moko-poi:fix/update-put-endpoint-to-restful). It seems to follow the typical process for contributing, but is there still an issue with this approach? If another method is needed, could you please provide more specific instructions? Thank you!

**Comment by aliciascott** [comment]
ok strange, let me see if i'm able to force merge this.

**Pull request merged**
