### PR TITLE
multicode examples

### PR DESCRIPTION
**Pull request by davidejones**
### What does this PR do?

- Displays multiple request body json examples (in an accordion to switch)
- Display multiple curl examples using the different request body json examples (in an accordion to switch)

### Preview

https://docs-staging.datadoghq.com/david.jones/multicode-examples/api/latest/events/#post-an-event
https://docs-staging.datadoghq.com/david.jones/multicode-examples/api/latest/logs/#aggregate-events
https://docs-staging.datadoghq.com/david.jones/multicode-examples/api/latest/synthetics/#create-an-api-test

Lots of examples
https://docs-staging.datadoghq.com/david.jones/multicode-examples/api/latest/dashboards/#create-a-new-dashboard

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by therve** [comment]
Looks great! I noticed that the tab appears sometimes randomly when there is only one example.

https://docs-staging.datadoghq.com/david.jones/multicode-examples/api/latest/dashboards/#get-a-dashboard on python/others but not curl

https://docs-staging.datadoghq.com/david.jones/multicode-examples/api/latest/dashboards/#delete-dashboards on curl but not others.

**Comment by davidejones** [comment]
Thanks for the feedback, I believe that's fixed now @therve

**Comment by urseberry** [comment]
On the Dashboards page, under Get All Invitations for a shared Dashboard (https://docs-staging.datadoghq.com/david.jones/multicode-examples/api/latest/dashboards/#get-all-invitations-for-a-shared-dashboard), under the Code Example, when I first click the Ruby tab, then the Curl tab, only the Curl tab is shown and the other tabs disappear. Screenshot: https://share.getcloudapp.com/6quZg96p

**Review by urseberry — APPROVED** [review]
Spot checked some pages. Looks good!

**Comment by therve** [comment]
Thanks David, I'm still seeing some slightly inconsistent tabs I think? It's showing on "Get a dashboard" but not "Update a dashboard" for example. Do we want to show the tab when we have a single example?

**Comment by davidejones** [comment]
@therve I've updated to be more consistent, let me know what you think

**Review by bgdeutsch — APPROVED** [review]

**Pull request merged**
