### PR TITLE
Pull search results from Algolia

### PR DESCRIPTION
**Pull request by mstbbs**
# purpose

send search requests to the algolia powered universal search page.

# preview site

https://d2cx6t4ssmwdrv.cloudfront.net/michaelw/forward-search-algolia/

### CODE REVIEW

**Comment by mstbbs** [comment]
I will also orient Gus (and whoever else is interested) with Algolia. Baklava should have control over their own indexes.

**Comment by l0k0ms** [comment]
@mstbbs What I would note is that the “docs” column does not go at the same height than the other columns and that there lack spaces between sentence fragments in the search results https://cl.ly/2H3s0R3Q3X0Z do you know why?

**Comment by mstbbs** [comment]
@irabinovitch @l0k0ms - I have updated the preview text to the following logic:

- _If_ a description exists for the page, then we use the description
- _else_ we take the first paragraph (`<p>`) 

https://d2cx6t4ssmwdrv.cloudfront.net/michaelw/forward-search-algolia/search/?s=docker

Have a look and let me know.

**Comment by l0k0ms** [comment]
@mstbbs LGTM for me. Nicely done !

**Pull request merged**
