### PR TITLE
DEBUG-2334 Ruby DI documentation page

### PR DESCRIPTION
**Pull request by p-datadog**
### What does this PR do? What is the motivation?

Adds Ruby to the dynamic instrumentation languages.

### Merge instructions

Merge readiness:
- [ ] Ready for merge

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### CODE REVIEW

**Review by aliciascott — APPROVED** [review]
looks good!

**Comment by aliciascott** [comment]
Thanks @p-datadog approved, please add a comment with `/merge` when you are ready to merge this , thanks!

**Review by brett0000FF — APPROVED** [review]
Thanks!

**Pull request merged**
