### PR TITLE
Homepage update 2.0

### PR DESCRIPTION
**Pull request by zbayoff**
### What does this PR do?
New home page for Docs. 

### Motivation
https://trello.com/c/BWTUP4rR/3929-new-design-for-docs-front-page

### Preview link
https://docs-staging.datadoghq.com/zach/homepage-update/

### CODE REVIEW

**Comment by ruthnaebeck** [comment]
I'm concerned with accessibility of the search button color on the banner background color:
https://webaim.org/resources/contrastchecker/?fcolor=B325B5&bcolor=8A24B3

**Comment by zbayoff** [comment]
@ruthnaebeck this is fixed in preview per Chris's comments in the Trello Card.

**Comment by ruthnaebeck** [comment]
> @ruthnaebeck this is fixed in preview per Chris's comments in the Trello Card.

It's better but it is still failing:
https://webaim.org/resources/contrastchecker/?fcolor=B325B5&bcolor=6623B1

**Comment by zbayoff** [comment]
> > @ruthnaebeck this is fixed in preview per Chris's comments in the Trello Card.
> 
> It's better but it is still failing:
> https://webaim.org/resources/contrastchecker/?fcolor=B325B5&bcolor=6623B1

This accessibility test is for text on the background color. Does this apply in our case, as the text is white?

**Comment by ruthnaebeck** [comment]
> This accessibility test is for text on the background color. Does this apply in our case, as the text is white?

See the third section `Graphical Objects and User Interface Components`
https://cl.ly/c410a78eecb0

**Comment by apigirl** [comment]
just noticed that the icon is missing for the API tile

**Pull request merged**
