### PR TITLE
[DOCS-4723] Add instructions to run the Jenkins plugin Agentless

### PR DESCRIPTION
**Pull request by albertvaka**
### What does this PR do?
Adds setup instructions for Agentless mode (in addition to the existing "Agentful" mode) for the Datadog Jenkins plugin.

### Motivation
Agentless mode wasn't previously supported for CI Visibility but it is now.

### Additional notes
It's not possible to add tabs within tabs, so I've turned the existing tabs into sections to add tabs for agentless/agentful, like we do in the [CI Visibility tracer setup docs](https://docs.datadoghq.com/continuous_integration/tests/java/?tab=onpremisesciproviderdatadogagent).

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by albertvaka** [comment]
It seems it's not possible to add tabs within tabs, I'll need to rewrite this somehow to remove the nested tabs.

**Comment by buraizu** [comment]
Created DOCS-4723 to review

**Comment by hestonhoffman** [comment]
Hi @albertvaka, I pushed up some edits. Once the checks pass, I'll merge this in!

**Review by hestonhoffman — APPROVED** [review]

**Comment by albertvaka** [comment]
Thanks! You are awesome 🥳

**Pull request merged**
