### PR TITLE
Update description of `view.load_event` in `data_collected.md`

### PR DESCRIPTION
**Pull request by dsem**
### What does this PR do?
Changes the description of `view.load_event` to clarify the metric measures time, not a count.

### Motivation
The description of `view.load_event` implied that the value was a number that counted the times the event was fired. It appears the metric is actually tracking the time until the load event is fired (though I can't know that for sure).

### Preview
not available

### Additional Notes
Again, I hope the updated description is accurate but I think only a member of the Datadog organization can verify.

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by apigirl** [comment]
hi @dsem, thanks for this update! we're taking a look at it

**Review by bcaudan — APPROVED** [review]
LGTM, it could worth clarifying the other timings (dom content loaded, dom complete, ...) in the same way then

**Review by amina196 — APPROVED** [review]
spoke with Bastien and decided this PR is good to go. Many thanks to the contributor for making our documentation even more helpful to our users.

**Review by alai97 — APPROVED** [review]

**Comment by alai97** [comment]
Thanks for the PR and your patience, @dsem!

**Pull request merged**
