### PR TITLE
Update profiling namespacing for ddtrace 1.0

### PR DESCRIPTION
**Pull request by marcotc**
### What does this PR do?

This PR updates the profiler `require` path after changes to `ddtrace`'s namespacing scheme in the coming 1.0 release: https://github.com/DataDog/dd-trace-rb/pull/1849

The only namespace change applicable to our documentation is the profiler's directory being moved from `ddtrace/profiling` to `datadog/profiling`.

### Preview

https://docs-staging.datadoghq.com/marcotc/namespace-profiler/tracing/profiler/enabling/ruby/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by alai97 — APPROVED** [review]

**Comment by alai97** [comment]
Documentation PR approved to merge, waiting for mid-next week!

**Comment by ivoanjo** [comment]
Note that this shouldn't be merged until we release dd-trace-rb 1.0.0 as the new instructions will not work until we do the release.

**Review by ivoanjo — APPROVED** [review]

**Review by ivoanjo — CHANGES_REQUESTED** [review]
Actually on closer look, that `Datadog.configure` block is outdated by the 1.0 configuration changes as well.

There's ongoing talk about revisiting this, but if the current 1.0 proposal stays, we'll need to update the configure block.

**Comment by marcotc** [comment]
Superseded by #13871

**Pull request closed without merging**
