### PR TITLE
Update logs_to_metrics.md

### PR DESCRIPTION
**Pull request by taromn**
### What does this PR do? What is the motivation?

This PR updates Japanese doc, based on English doc.

[EN]
To generate a new log-based metric:

1. Navigate to the [Generate Metrics][5] page.
1. Select the **Generate Metrics** tab.
1. Click **+New Metric**.

↓↓↓

[JP]
ログベースのメトリクスを新しく生成するための手順は下記となります:

1. [Generate Metrics][6] ページへ移動します。
1. **Generate Metrics** タブが選択されていることを確認してください。
1. **+New Metric** をクリックします。

[EN] https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/#generate-a-log-based-metric
[JP] https://docs.datadoghq.com/ja/logs/log_configuration/logs_to_metrics/#%E3%83%AD%E3%82%B0%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E3%83%A1%E3%83%88%E3%83%AA%E3%82%AF%E3%82%B9%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by michaelcretzman — APPROVED** [review]
Approved.
Please remember to name branches using our convention:
https://github.com/DataDog/documentation?tab=readme-ov-file#datadog-staff

**Comment by taromn** [comment]
Thank you @michaelcretzman,
To merge the change, I need to make another PR that has the correct naming convention, right?

**Comment by michaelcretzman** [comment]
@taromn no, we can merge this PR. We just can't generate a build preview.

If you're confident that it's good to go, I can merge it.

**Comment by taromn** [comment]
@michaelcretzman,
I believe it's good to go.
merge this PR please, thanks.

**Pull request merged**
