### PR TITLE
Increases Desktop content area on Docs to 1440px

### PR DESCRIPTION
**Pull request by nsollecito**
### What does this PR do?
Increases the content area width for Docs pages to 1440px

### Motivation
Requests to take advantage of more real estate on larger screens, giving tables and graphics more horizontal space and reduce text wrapping
https://trello.com/c/tk13ubuf

### Preview

Check pages/nav:
https://docs-staging.datadoghq.com/nsollecito/body-width/

### Additional Notes
Ensure there are no issues with other breakpoints. 

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by davidejones — APPROVED** [review]

**Comment by ruthnaebeck** [comment]
Hello @nsollecito!
Because the page content is wider the hotjar feedback button is running right up against the "ON THIS PAGE" content. Is it easy to move? There's more space for it here: https://a.cl.ly/12uPgkn1

**Comment by nsollecito** [comment]
@ruthnaebeck there might be an option to change the placement in Hotjar. Doesn't look like I can control that on our end (I also don't have a login to the Hotjar UI to play around with the settings but here's what I found in case that's something you can adjust: https://help.hotjar.com/hc/en-us/articles/115011760268#custom_placement

If not, we can add some padding to the toc container and prevent the overlap as another option

**Comment by ruthnaebeck** [comment]
> @ruthnaebeck there might be an option to change the placement in Hotjar. Doesn't look like I can control that on our end (I also don't have a login to the Hotjar UI to play around with the settings but here's what I found in case that's something you can adjust: [help.hotjar.com/hc/en-us/articles/115011760268#custom_placement](https://help.hotjar.com/hc/en-us/articles/115011760268#custom_placement)
> 
> If not, we can add some padding to the toc container and prevent the overlap as another option

@nsollecito - Kaylyn was able to add you to Hotjar.

**Comment by nsollecito** [comment]
thanks @ruthnaebeck! I wasn't able to get anywhere with the Hotjar config so I added some padding to the toc and that helps a bit. Let me know if you see any other issues.

**Review by ruthnaebeck — APPROVED** [review]
👍  - Ready to merge @nsollecito?

**Comment by nsollecito** [comment]
@ruthnaebeck good to go.. i'll keep an eye out for anything that comes up

**Pull request merged**
