### PR TITLE
add korean language - [WEB-3966]

### PR DESCRIPTION
**Pull request by StefonSimmons**
### What does this PR do?

- adds korean language (`ko`) to `LANGUAGE` dropdown. 
- minor ja change to fix a bug 
- algolia changes to return korean results when on ko site.

### Motivation

https://datadoghq.atlassian.net/jira/software/projects/WEB/boards/102?selectedIssue=WEB-3966

### Preview

https://docs-staging.datadoghq.com/david.jones/web-3519/ko/

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Comment by rtrieu** [comment]
Created DOCS-6132 for a more in-depth editorial review.

**Review by apigirl — APPROVED** [review]

**Review by bgdeutsch — CHANGES_REQUESTED** [review]
seeing some broken images here: https://docs-staging.datadoghq.com/david.jones/web-3519/ko/tracing/guide/.  these are broken for all languages but they work in prod currently.

**Comment by StefonSimmons** [comment]
> seeing some broken images here: https://docs-staging.datadoghq.com/david.jones/web-3519/ko/tracing/guide/. these are broken for all languages but they work in prod currently.
@bgdeutsch these work locally and on prod but not in preview. I believe it has to do with the way they are sourced/stored locally.

**Review by bgdeutsch — APPROVED** [review]
checked various pages.   language dropdown (including API pages), placeholder page generation, left side nav, and algolia search all seem to be working as expected.   this LGTM 👍

**Pull request merged**
