### PR TITLE
[DOCS-8947] Add links to architecture docs

### PR DESCRIPTION
**Pull request by maycmlee**
### What does this PR do? What is the motivation?

Adds links to Architecture docs.

[DOCS-8947](https://datadoghq.atlassian.net/browse/DOCS-8947)

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

[DOCS-8947]: https://datadoghq.atlassian.net/browse/DOCS-8947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by drichards-87 — APPROVED** [review]
Approved. Also noting that the PR was removed from the merge queue. I'm not sure if that was intentional or not, so I'll let you re-add it to the queue.

**Comment by maycmlee** [comment]
> Approved. Also noting that the PR was removed from the merge queue. I'm not sure if that was intentional or not, so I'll let you re-add it to the queue.

oh interesting.. i wonder if it times out. Thanks for the heads up!

**Pull request merged**
