### PR TITLE
Fix RUM script example

### PR DESCRIPTION
**Pull request by cchantep**
### Preview

https://docs-staging.datadoghq.com/<BRANCH_NAME>/<PATH>

### Additional Notes

---

### Reviewer checklist
- [ ] Review the changed files.
- [ ] Review the URLs listed in the [Preview](#preview) section.
- [ ] Check images for PII
- [ ] Review any mentions of "Contact Datadog support" for internal support documentation.

### CODE REVIEW

**Review by hdelaby — APPROVED** [review]
Nice catch! Thank you :)

**Review by hdelaby — CHANGES_REQUESTED** [review]
Actually, the same change needs to be made on line 89 and line 105.

**Review by bcaudan — APPROVED** [review]
nice catch

**Review by cswatt — APPROVED** [review]

**Comment by cswatt** [comment]
@cchantep thanks for the help!

**Pull request merged**
