### PR TITLE
Consolidate service config docs

### PR DESCRIPTION
**Pull request by janine-c**
### What does this PR do? What is the motivation?

Consolidating the [Understanding Your Service Configuration](https://docs.datadoghq.com/service_catalog/guides/understanding-service-configuration/) topic into the [Manage a Service](https://docs.datadoghq.com/service_catalog/manage/) topic, as drafted by Brooke in her excellent [Google doc](https://docs.google.com/document/d/1zvduiFCrEKEGvclsC1oci3vjsRemYjTj2mDW3WnT17A/edit?pli=1&tab=t.0#heading=h.kz3lh7tihkqn).

### Merge instructions

Merge queue is enabled in this repo. To have it automatically merged after it receives the required reviews, create the PR (from a branch that follows the `<yourname>/description` naming convention) and then add the following PR comment:

```
/merge
```

### Additional notes

This is my first time implementing redirects and deleting a topic. Everything looks fine on my local build, but please let me know if I missed any best practices or links to the deleted topic in other places I didn't think to look.

### CODE REVIEW

**Comment by crunchypistachiobutter** [comment]
overall LGTM, only change needed is to place it as the 3rd section on the page, below the following 

https://docs-staging.datadoghq.com/janine.chan/docs-9355-service-catalog-consolidate-topics/service_catalog/manage/#assigning-an-owner-to-a-service

https://docs-staging.datadoghq.com/janine.chan/docs-9355-service-catalog-consolidate-topics/service_catalog/manage/#determining-and-communicating-service-levels

**Comment by janine-c** [comment]
@crunchypistachiobutter Thanks for flagging that! ✅

**Review by crunchypistachiobutter — APPROVED** [review]
thank you for incorporating the changes! Ship it!

**Review by rtrieu — APPROVED** [review]
This looks good!

**Pull request merged**
