### PR TITLE
Fix Node.js spelling

### PR DESCRIPTION
**Pull request by watson**
### What does this PR do? What is the motivation?

Fix the spelling of the Node.js programming language. Several places it's currently spelled incorrectly: `NodeJS` / `NodeJs` / `Nodejs`. The correct spelling is `Node.js`.

### Merge instructions

- [x] Please merge after reviewing

### Additional notes

When viewing the preview pages generated, you can see that this PR doesn't change the spelling of Node.js in the title of the [`/integrations/node/`](https://docs-staging.datadoghq.com/watson/nodejs/integrations/node/) page. I think that's because that page isn't defined in this repo, but instead in the `dogweb` repo. I've tried to address that in this PR: https://github.com/DataDog/dogweb/pull/129416

I'm not 100% sure about the following changes. Please take extra care when reviewing those.
- Markdown changes to `{{% tab "..." %}}`.
- Changes to `config/_default/menus/main.*.yaml`.

### CODE REVIEW

**Review by brett0000FF — APPROVED** [review]
Thanks for fixing these!

**Comment by brett0000FF** [comment]
@watson - Looks great! Thanks for making these changes. Just as an FYI for next time, the non-English files get updated through our translation service. So changing them here doesn't hurt anything, but it'll get overwritten after merging. (Then it will update to be correct after the files are reviewed by our translators).

**Review by devindford — APPROVED** [review]
LGTM

**Pull request merged**
