### PR TITLE
Update datadog-aas-linux version in azure_app_services_linux.md

### PR DESCRIPTION
**Pull request by apiarian-datadog**
### What does this PR do? What is the motivation?

Update the version of the DataDog/datadog-aas-linux datadog_wrapper to the latest.

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Comment by apiarian-datadog** [comment]
replaces https://github.com/DataDog/documentation/pull/24371

**Review by drichards-87 — APPROVED** [review]
Looks good! Do we need to get someone from the Serverless team to approve before we merge this?

**Review by brandondatadog — APPROVED** [review]

**Comment by drichards-87** [comment]
@apiarian-datadog Just checking in on this PR again. It looks like we've gotten the approvals needed. Am I good to merge this now?

**Comment by apiarian-datadog** [comment]
> @apiarian-datadog Just checking in on this PR again. It looks like we've gotten the approvals needed. Am I good to merge this now?

Yes, thank you!

**Pull request merged**
