### PR TITLE
[DOCS-7755] Reorganize Service Catalog Pages

### PR DESCRIPTION
**Pull request by brett0000FF**
### What does this PR do? What is the motivation?

Reorganize Service Catalog nav and pages.
No new content--just moving sections and pages around.

### Merge instructions

- [ ] Please merge after reviewing

### Additional notes

https://datadoghq.atlassian.net/browse/DOCS-7825

### CODE REVIEW

**Comment by brett0000FF** [comment]
@crunchypistachiobutter - Please take a look and let me know if this is what you are looking for 🙏 . I took some liberties to condense the left-nav titles so they don't overflow onto multiple lines. Any and all feedback is welcome!

**Comment by crunchypistachiobutter** [comment]
small nit: changing 'Service Definitions and Support' to just 'Service Definitions'

**Comment by crunchypistachiobutter** [comment]
otherwise LGTM

**Comment by crunchypistachiobutter** [comment]
commented - one nit but otherwise LGTM

**Pull request merged**
