### PR TITLE
Update save-cpu-in-production-with-go-pgo.md

### PR DESCRIPTION
**Pull request by felixge**
### What does this PR do? What is the motivation?

Change up to 15% to up to 14% which is the [official number](https://go.dev/doc/pgo) given by the Go compiler team. Rounding this up might make us look bad.

### Merge instructions

- [ ] Please merge after reviewing

### CODE REVIEW

**Review by gturbat — APPROVED** [review]

**Comment by hestonhoffman** [comment]
@felixge let me know if this is good to merge!

**Comment by felixge** [comment]
> @felixge let me know if this is good to merge!

good to merge from my PoV. (Not sure about the CI failure)

**Comment by felixge** [comment]
@hestonhoffman can we get this merged?

**Comment by hestonhoffman** [comment]
@felixge Sorry, this one fell off my radar

**Comment by felixge** [comment]
Np, thanks for the merge 🙇

**Pull request merged**
