### PR TITLE
Reformat markdown reference links for unification/consistency

### PR DESCRIPTION
**Pull request by svmhdvn**
### What does this PR do?
This PR introduces a new script to reformat the reference-formatted links in markdown files to do the following things:
- Remove duplicate link definitions and references
- Move all link definitions to the bottom (footer) of the page to avoid per-paragraph link definitions
- Reorder link definitions numerically from top to bottom
- Add link references wherever inline non-anchor links are used
- Ensures that closable shortcodes (e.g. `{{% tab %}}`, `{{% table %}}`, etc.) have their own link definition scope (constraint with hugo's markdown renderer)

### Motivation
- The contributing guidelines state:
> Links must be specified using the reference format (i.e. in the footnote) in order to aid the translation process.
- Link formatting inconsistencies in larger files with lots of commit history and content
- Requested by @l0k0ms.

### Preview link
https://docs-staging.datadoghq.com/svmhdvn/links-fix

### Additional Notes
- codeblock formatting in `content/graphing/graphing_json.md` was changed for consistency with other files
- the `https://docs.datadoghq.com`-prefix was removed from many internal docs links
- manually edited `content/graphing/graphing_json.md` to fix formatting that was giving the script issues.

### CODE REVIEW

**Comment by svmhdvn** [comment]
Ready for initial review.

**Comment by svmhdvn** [comment]
I could also hardcode the `local/githooks` folder, since `local/*` is being checked into git anyway.

I will look into and fix the encoding issue though.

**Comment by l0k0ms** [comment]
@svmhdvn yup, hard-coding the link may be the best way to go, there is no real reason, for now, to have it configurable.

**Comment by svmhdvn** [comment]
Encoding issue in staging build is now fixed.

**Pull request merged**
